-- Commander_Talents - WARLOCK talent data (GENERATED 2026-08-04).
-- TBC 2.4.3 final talent state. Regenerate via an agent pass against
-- prompts/commander-talents.md; after any hand-edit, re-run
-- Harness/validate_class_data.lua.

CommanderTalentsData.Classes.WARLOCK = {
    trees = {
        {
            name = "Affliction", bg = "WarlockCurses",
            talents = {
                { name = "Suppression", icon = "spell_shadow_unsummonbuilding", row = 1, col = 2, max = 5,
                  ranks = {
                    "Reduces the chance for enemies to resist your Affliction spells by 2%.",
                    "Reduces the chance for enemies to resist your Affliction spells by 4%.",
                    "Reduces the chance for enemies to resist your Affliction spells by 6%.",
                    "Reduces the chance for enemies to resist your Affliction spells by 8%.",
                    "Reduces the chance for enemies to resist your Affliction spells by 10%.",
                  } },
                { name = "Improved Corruption", icon = "spell_shadow_abominationexplosion", row = 1, col = 3, max = 5,
                  ranks = {
                    "Reduces the casting time of your Corruption spell by 0.4 sec.",
                    "Reduces the casting time of your Corruption spell by 0.8 sec.",
                    "Reduces the casting time of your Corruption spell by 1.2 sec.",
                    "Reduces the casting time of your Corruption spell by 1.6 sec.",
                    "Reduces the casting time of your Corruption spell by 2 sec.",
                  } },
                { name = "Improved Curse of Weakness", icon = "spell_shadow_curseofmannoroth", row = 2, col = 1, max = 2,
                  ranks = {
                    "Increases the effect of your Curse of Weakness by 10%.",
                    "Increases the effect of your Curse of Weakness by 20%.",
                  } },
                { name = "Improved Drain Soul", icon = "spell_shadow_haunting", row = 2, col = 2, max = 2,
                  ranks = {
                    "Returns 7% of your maximum mana if the target is killed by you while you drain its soul. In addition, your Affliction spells generate 5% less threat.",
                    "Returns 15% of your maximum mana if the target is killed by you while you drain its soul. In addition, your Affliction spells generate 10% less threat.",
                  } },
                { name = "Improved Life Tap", icon = "spell_shadow_burningspirit", row = 2, col = 3, max = 2,
                  ranks = {
                    "Increases the amount of Mana awarded by your Life Tap spell by 10%.",
                    "Increases the amount of Mana awarded by your Life Tap spell by 20%.",
                  } },
                { name = "Soul Siphon", icon = "spell_shadow_lifedrain02", row = 2, col = 4, max = 2,
                  ranks = {
                    "Increases the amount drained by your Drain Life spell by an additional 2% for each Affliction effect on the target, up to a maximum of 24% additional effect.",
                    "Increases the amount drained by your Drain Life spell by an additional 4% for each Affliction effect on the target, up to a maximum of 60% additional effect.",
                  } },
                { name = "Improved Curse of Agony", icon = "spell_shadow_curseofsargeras", row = 3, col = 1, max = 2,
                  ranks = {
                    "Increases the damage done by your Curse of Agony by 5%.",
                    "Increases the damage done by your Curse of Agony by 10%.",
                  } },
                { name = "Fel Concentration", icon = "spell_shadow_fingerofdeath", row = 3, col = 2, max = 5,
                  ranks = {
                    "Gives you a 14% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.",
                    "Gives you a 28% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.",
                    "Gives you a 42% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.",
                    "Gives you a 56% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.",
                    "Gives you a 70% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.",
                  } },
                { name = "Amplify Curse", icon = "spell_shadow_contagion", row = 3, col = 3, max = 1,
                  ranks = {
                    "Increases the effect of your next Curse of Doom or Curse of Agony by 50%, or your next Curse of Exhaustion by an additional 20%. Lasts 30 sec.",
                  } },
                { name = "Grim Reach", icon = "spell_shadow_callofbone", row = 4, col = 1, max = 2,
                  ranks = {
                    "Increases the range of your Affliction spells by 10%.",
                    "Increases the range of your Affliction spells by 20%.",
                  } },
                { name = "Nightfall", icon = "spell_shadow_twilight", row = 4, col = 2, max = 2,
                  ranks = {
                    "Gives your Corruption and Drain Life spells a 2% chance to cause you to enter a Shadow Trance state after damaging the opponent. The Shadow Trance state reduces the casting time of your next Shadow Bolt spell by 100%.",
                    "Gives your Corruption and Drain Life spells a 4% chance to cause you to enter a Shadow Trance state after damaging the opponent. The Shadow Trance state reduces the casting time of your next Shadow Bolt spell by 100%.",
                  } },
                { name = "Empowered Corruption", icon = "spell_shadow_abominationexplosion", row = 4, col = 4, max = 3,
                  ranks = {
                    "Your Corruption spell gains an additional 12% of your bonus spell damage effects.",
                    "Your Corruption spell gains an additional 24% of your bonus spell damage effects.",
                    "Your Corruption spell gains an additional 36% of your bonus spell damage effects.",
                  } },
                { name = "Shadow Embrace", icon = "spell_shadow_shadowembrace", row = 5, col = 1, max = 5,
                  ranks = {
                    "Your Corruption, Curse of Agony, Siphon Life and Seed of Corruption spells also cause the Shadow Embrace effect, which reduces physical damage caused by 1%.",
                    "Your Corruption, Curse of Agony, Siphon Life and Seed of Corruption spells also cause the Shadow Embrace effect, which reduces physical damage caused by 2%.",
                    "Your Corruption, Curse of Agony, Siphon Life and Seed of Corruption spells also cause the Shadow Embrace effect, which reduces physical damage caused by 3%.",
                    "Your Corruption, Curse of Agony, Siphon Life and Seed of Corruption spells also cause the Shadow Embrace effect, which reduces physical damage caused by 4%.",
                    "Your Corruption, Curse of Agony, Siphon Life and Seed of Corruption spells also cause the Shadow Embrace effect, which reduces physical damage caused by 5%.",
                  } },
                { name = "Siphon Life", icon = "spell_shadow_requiem", row = 5, col = 2, max = 1,
                  ranks = {
                    "Transfers 15 health from the target to the caster every 3 sec. Lasts 30 sec.",
                  } },
                { name = "Curse of Exhaustion", icon = "spell_shadow_grimward", row = 5, col = 3, max = 1, req = "Amplify Curse",
                  ranks = {
                    "Reduces the target's movement speed by 30% for 12 sec. Only one Curse per Warlock can be active on any one target.",
                  } },
                { name = "Shadow Mastery", icon = "spell_shadow_shadetruesight", row = 6, col = 2, max = 5, req = "Siphon Life",
                  ranks = {
                    "Increases the damage dealt or life drained by your Shadow spells by 2%.",
                    "Increases the damage dealt or life drained by your Shadow spells by 4%.",
                    "Increases the damage dealt or life drained by your Shadow spells by 6%.",
                    "Increases the damage dealt or life drained by your Shadow spells by 8%.",
                    "Increases the damage dealt or life drained by your Shadow spells by 10%.",
                  } },
                { name = "Contagion", icon = "spell_shadow_painfulafflictions", row = 7, col = 2, max = 5,
                  ranks = {
                    "Increases the damage of Curse of Agony, Corruption and Seed of Corruption by 1% and reduces the chance your Affliction spells will be dispelled by an additional 6%.",
                    "Increases the damage of Curse of Agony, Corruption and Seed of Corruption by 2% and reduces the chance your Affliction spells will be dispelled by an additional 12%.",
                    "Increases the damage of Curse of Agony, Corruption and Seed of Corruption by 3% and reduces the chance your Affliction spells will be dispelled by an additional 18%.",
                    "Increases the damage of Curse of Agony, Corruption and Seed of Corruption by 4% and reduces the chance your Affliction spells will be dispelled by an additional 24%.",
                    "Increases the damage of Curse of Agony, Corruption and Seed of Corruption by 5% and reduces the chance your Affliction spells will be dispelled by an additional 30%.",
                  } },
                { name = "Dark Pact", icon = "spell_shadow_darkritual", row = 7, col = 3, max = 1,
                  ranks = {
                    "Drains 305 of your pet's Mana, returning 100% to you.",
                  } },
                { name = "Improved Howl of Terror", icon = "spell_shadow_deathscream", row = 8, col = 1, max = 2,
                  ranks = {
                    "Reduces the casting time of your Howl of Terror spell by 0.8 sec.",
                    "Reduces the casting time of your Howl of Terror spell by 1.5 sec.",
                  } },
                { name = "Malediction", icon = "spell_shadow_curseofachimonde", row = 8, col = 3, max = 3,
                  ranks = {
                    "Increases the damage bonus effect of your Curse of the Elements spell by an additional 1%.",
                    "Increases the damage bonus effect of your Curse of the Elements spell by an additional 2%.",
                    "Increases the damage bonus effect of your Curse of the Elements spell by an additional 3%.",
                  } },
                { name = "Unstable Affliction", icon = "spell_shadow_unstableaffliction_3", row = 9, col = 2, max = 1, req = "Contagion",
                  ranks = {
                    "Shadow energy slowly destroys the target, causing 660 damage over 18 sec. In addition, if the Unstable Affliction is dispelled it will cause 990 damage to the dispeller and silence them for 5 sec.",
                  } },
            },
        },
        {
            name = "Demonology", bg = "WarlockSummoning",
            talents = {
                { name = "Improved Healthstone", icon = "inv_stone_04", row = 1, col = 1, max = 2,
                  ranks = {
                    "Increases the amount of Health restored by your Healthstone by 10%.",
                    "Increases the amount of Health restored by your Healthstone by 20%.",
                  } },
                { name = "Improved Imp", icon = "spell_shadow_summonimp", row = 1, col = 2, max = 3,
                  ranks = {
                    "Increases the effect of your Imp's Firebolt, Fire Shield, and Blood Pact spells by 10%.",
                    "Increases the effect of your Imp's Firebolt, Fire Shield, and Blood Pact spells by 20%.",
                    "Increases the effect of your Imp's Firebolt, Fire Shield, and Blood Pact spells by 30%.",
                  } },
                { name = "Demonic Embrace", icon = "spell_shadow_metamorphosis", row = 1, col = 3, max = 5,
                  ranks = {
                    "Increases your total Stamina by 3% but reduces your total Spirit by 1%.",
                    "Increases your total Stamina by 6% but reduces your total Spirit by 2%.",
                    "Increases your total Stamina by 9% but reduces your total Spirit by 3%.",
                    "Increases your total Stamina by 12% but reduces your total Spirit by 4%.",
                    "Increases your total Stamina by 15% but reduces your total Spirit by 5%.",
                  } },
                { name = "Improved Health Funnel", icon = "spell_shadow_lifedrain", row = 2, col = 1, max = 2,
                  ranks = {
                    "Increases the amount of Health transferred by your Health Funnel spell by 10% and reduces the initial health cost by 10%.",
                    "Increases the amount of Health transferred by your Health Funnel spell by 20% and reduces the initial health cost by 20%.",
                  } },
                { name = "Improved Voidwalker", icon = "spell_shadow_summonvoidwalker", row = 2, col = 2, max = 3,
                  ranks = {
                    "Increases the effectiveness of your Voidwalker's Torment, Consume Shadows, Sacrifice and Suffering spells by 10%.",
                    "Increases the effectiveness of your Voidwalker's Torment, Consume Shadows, Sacrifice and Suffering spells by 20%.",
                    "Increases the effectiveness of your Voidwalker's Torment, Consume Shadows, Sacrifice and Suffering spells by 30%.",
                  } },
                { name = "Fel Intellect", icon = "spell_holy_magicalsentry", row = 2, col = 3, max = 3,
                  ranks = {
                    "Increases the Intellect of your Imp, Voidwalker, Succubus, Incubus, Felhunter and Felguard by 5% and increases your maximum mana by 1%.",
                    "Increases the Intellect of your Imp, Voidwalker, Succubus, Incubus, Felhunter and Felguard by 10% and increases your maximum mana by 2%.",
                    "Increases the Intellect of your Imp, Voidwalker, Succubus, Incubus, Felhunter and Felguard by 15% and increases your maximum mana by 3%.",
                  } },
                { name = "Improved Succubus", icon = "spell_shadow_summonsuccubus", row = 3, col = 1, max = 3,
                  ranks = {
                    "Increases the effect of your Succubus' and Incubus' Lash of Pain and Soothing Kiss spells by 10%, and increases the duration of your Succubus' and Incubus' Seduction and Lesser Invisibility spells by 10%.",
                    "Increases the effect of your Succubus' and Incubus' Lash of Pain and Soothing Kiss spells by 20%, and increases the duration of your Succubus' and Incubus' Seduction and Lesser Invisibility spells by 20%.",
                    "Increases the effect of your Succubus' and Incubus' Lash of Pain and Soothing Kiss spells by 30%, and increases the duration of your Succubus' and Incubus' Seduction and Lesser Invisibility spells by 30%.",
                  } },
                { name = "Fel Domination", icon = "spell_nature_removecurse", row = 3, col = 2, max = 1,
                  ranks = {
                    "Your next Imp, Voidwalker, Succubus, Incubus, Felhunter or Felguard Summon spell has its casting time reduced by 5.5 sec and its Mana cost reduced by 50%.",
                  } },
                { name = "Fel Stamina", icon = "spell_shadow_antishadow", row = 3, col = 3, max = 3,
                  ranks = {
                    "Increases the Stamina of your Imp, Voidwalker, Succubus, Incubus, Felhunter and Felguard by 5% and increases your maximum health by 1%.",
                    "Increases the Stamina of your Imp, Voidwalker, Succubus, Incubus, Felhunter and Felguard by 10% and increases your maximum health by 2%.",
                    "Increases the Stamina of your Imp, Voidwalker, Succubus, Incubus, Felhunter and Felguard by 15% and increases your maximum health by 3%.",
                  } },
                { name = "Demonic Aegis", icon = "spell_shadow_ragingscream", row = 3, col = 4, max = 3,
                  ranks = {
                    "Increases the effectiveness of your Demon Armor and Fel Armor spells by 10%.",
                    "Increases the effectiveness of your Demon Armor and Fel Armor spells by 20%.",
                    "Increases the effectiveness of your Demon Armor and Fel Armor spells by 30%.",
                  } },
                { name = "Master Summoner", icon = "spell_shadow_impphaseshift", row = 4, col = 2, max = 2, req = "Fel Domination",
                  ranks = {
                    "Reduces the casting time of your Imp, Voidwalker, Succubus, Incubus, Felhunter and Fel Guard Summoning spells by 2 sec and the Mana cost by 20%.",
                    "Reduces the casting time of your Imp, Voidwalker, Succubus, Incubus, Felhunter and Fel Guard Summoning spells by 4 sec and the Mana cost by 40%.",
                  } },
                { name = "Unholy Power", icon = "spell_shadow_shadowworddominate", row = 4, col = 3, max = 5,
                  ranks = {
                    "Increases the damage done by your Voidwalker, Succubus, Incubus, Felhunter and Felguard's melee attacks and your Imp's Firebolt by 4%.",
                    "Increases the damage done by your Voidwalker, Succubus, Incubus, Felhunter and Felguard's melee attacks and your Imp's Firebolt by 8%.",
                    "Increases the damage done by your Voidwalker, Succubus, Incubus, Felhunter and Felguard's melee attacks and your Imp's Firebolt by 12%.",
                    "Increases the damage done by your Voidwalker, Succubus, Incubus, Felhunter and Felguard's melee attacks and your Imp's Firebolt by 16%.",
                    "Increases the damage done by your Voidwalker, Succubus, Incubus, Felhunter and Felguard's melee attacks and your Imp's Firebolt by 20%.",
                  } },
                { name = "Improved Enslave Demon", icon = "spell_shadow_enslavedemon", row = 5, col = 1, max = 2,
                  ranks = {
                    "Reduces the Attack Speed and Casting Speed penalty of your Subjugate Demon spell by 5% and reduces the resist chance by 5%.",
                    "Reduces the Attack Speed and Casting Speed penalty of your Subjugate Demon spell by 10% and reduces the resist chance by 10%.",
                  } },
                { name = "Demonic Sacrifice", icon = "spell_shadow_psychicscream", row = 5, col = 2, max = 1,
                  ranks = {
                    "When activated, sacrifices your summoned demon to grant you an effect that lasts 30 min. The effect is canceled if any Demon is summoned.\n\nImp: Increases your Fire damage by 15%.\n\nVoidwalker: Restores 2% of total health every 4 sec.\n\nSuccubus/Incubus: Increases your Shadow damage by 15%.\n\nFelhunter: Restores 3% of total mana every 4 sec.\n\nFelguard: Increases your Shadow damage by 10% and restores 2% of total mana every 4 sec.",
                  } },
                { name = "Master Conjuror", icon = "inv_ammo_firetar", row = 5, col = 4, max = 2,
                  ranks = {
                    "Increases the bonus Fire damage from Firestones and the Firestone effect by 15% and increases the spell critical strike rating bonus of your Spellstone by 15%.",
                    "Increases the bonus Fire damage from Firestones and the Firestone effect by 30% and increases the spell critical strike rating bonus of your Spellstone by 30%.",
                  } },
                { name = "Mana Feed", icon = "spell_shadow_manafeed", row = 6, col = 1, max = 3,
                  ranks = {
                    "When you gain mana from Drain Mana or Life Tap spells, your pet gains 33% of the mana you gain.",
                    "When you gain mana from Drain Mana or Life Tap spells, your pet gains 66% of the mana you gain.",
                    "When you gain mana from Drain Mana or Life Tap spells, your pet gains 100% of the mana you gain.",
                  } },
                { name = "Master Demonologist", icon = "spell_shadow_shadowpact", row = 6, col = 3, max = 5, req = "Unholy Power",
                  ranks = {
                    "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 4%.\n\nVoidwalker - Reduces physical damage taken by 2%.\n\nSuccubus/Incubus - Increases all damage caused by 2%.\n\nFelhunter - Increases all resistances by .2 per level.\n\nFelguard - Increases all damage caused by 1% and all resistances by .1 per level.",
                    "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 8%.\n\nVoidwalker - Reduces physical damage taken by 4%.\n\nSuccubus/Incubus - Increases all damage caused by 4%.\n\nFelhunter - Increases all resistances by .4 per level.\n\nFelguard - Increases all damage caused by 2% and all resistances by .2 per level.",
                    "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 12%.\n\nVoidwalker - Reduces physical damage taken by 6%.\n\nSuccubus/Incubus - Increases all damage caused by 6%.\n\nFelhunter - Increases all resistances by .6 per level.\n\nFelguard - Increases all damage caused by 3% and all resistances by .3 per level.",
                    "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 16%.\n\nVoidwalker - Reduces physical damage taken by 8%.\n\nSuccubus/Incubus - Increases all damage caused by 8%.\n\nFelhunter - Increases all resistances by .8 per level.\n\nFelguard - Increases all damage caused by 4% and all resistances by .4 per level.",
                    "Grants both the Warlock and the summoned demon an effect as long as that demon is active.\n\nImp - Reduces threat caused by 20%.\n\nVoidwalker - Reduces physical damage taken by 10%.\n\nSuccubus/Incubus - Increases all damage caused by 10%.\n\nFelhunter - Increases all resistances by 1 per level.\n\nFelguard - Increases all damage caused by 5% and all resistances by .5 per level.",
                  } },
                { name = "Demonic Resilience", icon = "spell_shadow_demonicfortitude", row = 7, col = 1, max = 3,
                  ranks = {
                    "Reduces the chance you'll be critically hit by melee and spells by 1% and reduces all damage your summoned demon takes by 5%.",
                    "Reduces the chance you'll be critically hit by melee and spells by 2% and reduces all damage your summoned demon takes by 10%.",
                    "Reduces the chance you'll be critically hit by melee and spells by 3% and reduces all damage your summoned demon takes by 15%.",
                  } },
                { name = "Soul Link", icon = "spell_shadow_gathershadows", row = 7, col = 2, max = 1, req = "Demonic Sacrifice",
                  ranks = {
                    "When active, 20% of all damage taken by the caster is taken by your Imp, Voidwalker, Succubus, Incubus, Felhunter, Felguard, or subjugated demon instead. That damage cannot be prevented. In addition, both the demon and master will inflict 5% more damage. Lasts as long as the demon is active and controlled.",
                  } },
                { name = "Demonic Knowledge", icon = "spell_shadow_improvedvampiricembrace", row = 7, col = 3, max = 3,
                  ranks = {
                    "Increases your spell damage by an amount equal to 4% of the total of your active demon's Stamina plus Intellect.",
                    "Increases your spell damage by an amount equal to 8% of the total of your active demon's Stamina plus Intellect.",
                    "Increases your spell damage by an amount equal to 12% of the total of your active demon's Stamina plus Intellect.",
                  } },
                { name = "Demonic Tactics", icon = "spell_shadow_demonictactics", row = 8, col = 2, max = 5,
                  ranks = {
                    "Increases melee and spell critical strike chance for you and your summoned demon by 1%.",
                    "Increases melee and spell critical strike chance for you and your summoned demon by 2%.",
                    "Increases melee and spell critical strike chance for you and your summoned demon by 3%.",
                    "Increases melee and spell critical strike chance for you and your summoned demon by 4%.",
                    "Increases melee and spell critical strike chance for you and your summoned demon by 5%.",
                  } },
                { name = "Summon Felguard", icon = "spell_shadow_summonfelguard", row = 9, col = 2, max = 1,
                  ranks = {
                    "Summons a Felguard under the command of the Warlock.",
                  } },
            },
        },
        {
            name = "Destruction", bg = "WarlockDestruction",
            talents = {
                { name = "Improved Shadow Bolt", icon = "spell_shadow_shadowbolt", row = 1, col = 2, max = 5,
                  ranks = {
                    "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 4% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.",
                    "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 8% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.",
                    "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 12% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.",
                    "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 16% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.",
                    "Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 20% until 4 non-periodic damage sources are applied. Effect lasts a maximum of 12 sec.",
                  } },
                { name = "Cataclysm", icon = "spell_fire_windsofwoe", row = 1, col = 3, max = 5,
                  ranks = {
                    "Reduces the Mana cost of your Destruction spells by 1%.",
                    "Reduces the Mana cost of your Destruction spells by 2%.",
                    "Reduces the Mana cost of your Destruction spells by 3%.",
                    "Reduces the Mana cost of your Destruction spells by 4%.",
                    "Reduces the Mana cost of your Destruction spells by 5%.",
                  } },
                { name = "Bane", icon = "spell_shadow_deathpact", row = 2, col = 2, max = 5,
                  ranks = {
                    "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.1 sec and your Soul Fire spell by 0.4 sec.",
                    "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.2 sec and your Soul Fire spell by 0.8 sec.",
                    "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.3 sec and your Soul Fire spell by 1.2 sec.",
                    "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.4 sec and your Soul Fire spell by 1.6 sec.",
                    "Reduces the casting time of your Shadow Bolt and Immolate spells by 0.5 sec and your Soul Fire spell by 2 sec.",
                  } },
                { name = "Aftermath", icon = "spell_fire_fire", row = 2, col = 3, max = 5,
                  ranks = {
                    "Gives your Destruction spells a 2% chance to daze the target for 5 sec.",
                    "Gives your Destruction spells a 4% chance to daze the target for 5 sec.",
                    "Gives your Destruction spells a 6% chance to daze the target for 5 sec.",
                    "Gives your Destruction spells a 8% chance to daze the target for 5 sec.",
                    "Gives your Destruction spells a 10% chance to daze the target for 5 sec.",
                  } },
                { name = "Improved Firebolt", icon = "spell_fire_firebolt", row = 3, col = 1, max = 2,
                  ranks = {
                    "Reduces the casting time of your Imp's Firebolt spell by 0.25 sec.",
                    "Reduces the casting time of your Imp's Firebolt spell by 0.5 sec.",
                  } },
                { name = "Improved Lash of Pain", icon = "spell_shadow_curse", row = 3, col = 2, max = 2,
                  ranks = {
                    "Reduces the cooldown of your Succubus' and Incubus' Lash of Pain spell by 3 sec.",
                    "Reduces the cooldown of your Succubus' and Incubus' Lash of Pain spell by 6 sec.",
                  } },
                { name = "Devastation", icon = "spell_fire_flameshock", row = 3, col = 3, max = 5,
                  ranks = {
                    "Increases the critical strike chance of your Destruction spells by 1%.",
                    "Increases the critical strike chance of your Destruction spells by 2%.",
                    "Increases the critical strike chance of your Destruction spells by 3%.",
                    "Increases the critical strike chance of your Destruction spells by 4%.",
                    "Increases the critical strike chance of your Destruction spells by 5%.",
                  } },
                { name = "Shadowburn", icon = "spell_shadow_scourgebuild", row = 3, col = 4, max = 1,
                  ranks = {
                    "Instantly blasts the target for 91 to 104 Shadow damage. If the target dies within 5 sec of Shadowburn, and yields experience or honor, the caster gains a Soul Shard.",
                  } },
                { name = "Intensity", icon = "spell_fire_lavaspawn", row = 4, col = 1, max = 2,
                  ranks = {
                    "Gives you a 35% chance to resist interruption caused by damage while casting or channeling any Destruction spell.",
                    "Gives you a 70% chance to resist interruption caused by damage while casting or channeling any Destruction spell.",
                  } },
                { name = "Destructive Reach", icon = "spell_shadow_corpseexplode", row = 4, col = 2, max = 2,
                  ranks = {
                    "Increases the range of your Destruction spells by 10% and reduces threat caused by Destruction spells by 5%.",
                    "Increases the range of your Destruction spells by 20% and reduces threat caused by Destruction spells by 10%.",
                  } },
                { name = "Improved Searing Pain", icon = "spell_fire_soulburn", row = 4, col = 4, max = 3,
                  ranks = {
                    "Increases the critical strike chance of your Searing Pain spell by 4%.",
                    "Increases the critical strike chance of your Searing Pain spell by 7%.",
                    "Increases the critical strike chance of your Searing Pain spell by 10%.",
                  } },
                { name = "Pyroclasm", icon = "spell_fire_volcano", row = 5, col = 1, max = 2, req = "Intensity",
                  ranks = {
                    "Gives your Rain of Fire, Hellfire, and Soul Fire spells a 13% chance to stun the target for 3 sec.",
                    "Gives your Rain of Fire, Hellfire, and Soul Fire spells a 26% chance to stun the target for 3 sec.",
                  } },
                { name = "Improved Immolate", icon = "spell_fire_immolation", row = 5, col = 2, max = 5,
                  ranks = {
                    "Increases the initial damage of your Immolate spell by 5%.",
                    "Increases the initial damage of your Immolate spell by 10%.",
                    "Increases the initial damage of your Immolate spell by 15%.",
                    "Increases the initial damage of your Immolate spell by 20%.",
                    "Increases the initial damage of your Immolate spell by 25%.",
                  } },
                { name = "Ruin", icon = "spell_shadow_shadowwordpain", row = 5, col = 3, max = 1, req = "Devastation",
                  ranks = {
                    "Increases the critical strike damage bonus of your Destruction spells by 100%.",
                  } },
                { name = "Nether Protection", icon = "spell_shadow_netherprotection", row = 6, col = 1, max = 3,
                  ranks = {
                    "After being hit with a Shadow or Fire spell, you have a 10% chance to become immune to Shadow and Fire spells for 4 sec.",
                    "After being hit with a Shadow or Fire spell, you have a 20% chance to become immune to Shadow and Fire spells for 4 sec.",
                    "After being hit with a Shadow or Fire spell, you have a 30% chance to become immune to Shadow and Fire spells for 4 sec.",
                  } },
                { name = "Emberstorm", icon = "spell_fire_selfdestruct", row = 6, col = 3, max = 5,
                  ranks = {
                    "Increases the damage done by your Fire spells by 2% and reduces the cast time of your Incinerate spell by 2%.",
                    "Increases the damage done by your Fire spells by 4%, and reduces the cast time of your Incinerate spell by 4%.",
                    "Increases the damage done by your Fire spells by 6%, and reduces the cast time of your Incinerate spell by 6%.",
                    "Increases the damage done by your Fire spells by 8%, and reduces the cast time of your Incinerate spell by 8%.",
                    "Increases the damage done by your Fire spells by 10%, and reduces the cast time of your Incinerate spell by 10%.",
                  } },
                { name = "Backlash", icon = "spell_fire_playingwithfire", row = 7, col = 1, max = 3,
                  ranks = {
                    "Increases your critical strike chance with spells by an additional 1% and gives you a 8% chance when hit by a physical attack to reduce the cast time of your next Shadow Bolt or Incinerate spell by 100%. This effect lasts 8 sec and will not occur more than once every 8 seconds.",
                    "Increases your critical strike chance with spells by an additional 2% and gives you a 16% chance when hit by a physical attack to reduce the cast time of your next Shadow Bolt or Incinerate spell by 100%. This effect lasts 8 sec and will not occur more than once every 8 seconds.",
                    "Increases your critical strike chance with spells by an additional 3% and gives you a 25% chance when hit by a physical attack to reduce the cast time of your next Shadow Bolt or Incinerate spell by 100%. This effect lasts 8 sec and will not occur more than once every 8 seconds.",
                  } },
                { name = "Conflagrate", icon = "spell_fire_fireball", row = 7, col = 2, max = 1, req = "Improved Immolate",
                  ranks = {
                    "Ignites a target that is already afflicted by your Immolate, dealing 249 to 316 Fire damage and consuming the Immolate spell.",
                  } },
                { name = "Soul Leech", icon = "spell_shadow_soulleech_3", row = 7, col = 3, max = 3,
                  ranks = {
                    "Gives your Shadow Bolt, Shadowburn, Soul Fire, Incinerate, Searing Pain and Conflagrate spells a 10% chance to return health equal to 20% of the damage caused.",
                    "Gives your Shadow Bolt, Shadowburn, Soul Fire, Incinerate, Searing Pain and Conflagrate spells a 20% chance to return health equal to 20% of the damage caused.",
                    "Gives your Shadow Bolt, Shadowburn, Soul Fire, Incinerate, Searing Pain and Conflagrate spells a 30% chance to return health equal to 20% of the damage caused.",
                  } },
                { name = "Shadow and Flame", icon = "spell_shadow_shadowandflame", row = 8, col = 2, max = 5,
                  ranks = {
                    "Your Shadow Bolt and Incinerate spells gain an additional 4% of your bonus spell damage effects.",
                    "Your Shadow Bolt and Incinerate spells gain an additional 8% of your bonus spell damage effects.",
                    "Your Shadow Bolt and Incinerate spells gain an additional 12% of your bonus spell damage effects.",
                    "Your Shadow Bolt and Incinerate spells gain an additional 16% of your bonus spell damage effects.",
                    "Your Shadow Bolt and Incinerate spells gain an additional 20% of your bonus spell damage effects.",
                  } },
                { name = "Shadowfury", icon = "spell_shadow_shadowfury", row = 9, col = 2, max = 1, req = "Shadow and Flame",
                  ranks = {
                    "Shadowfury is unleashed, causing 357 to 422 Shadow damage and stunning all enemies within 8 yds for 2 sec.",
                  } },
            },
        },
    },
    builds = {
        { key = "AFFLICTION", name = "Affliction", role = "CASTER",
          points = {
            [1] = {
                ["Suppression"] = 5,
                ["Improved Corruption"] = 5,
                ["Improved Drain Soul"] = 2,
                ["Improved Life Tap"] = 2,
                ["Soul Siphon"] = 2,
                ["Improved Curse of Agony"] = 2,
                ["Grim Reach"] = 2,
                ["Nightfall"] = 2,
                ["Empowered Corruption"] = 3,
                ["Siphon Life"] = 1,
                ["Shadow Mastery"] = 5,
                ["Contagion"] = 5,
                ["Dark Pact"] = 1,
                ["Malediction"] = 3,
                ["Unstable Affliction"] = 1,
            },
            [3] = {
                ["Improved Shadow Bolt"] = 5,
                ["Cataclysm"] = 4,
                ["Bane"] = 5,
                ["Devastation"] = 5,
                ["Shadowburn"] = 1,
            },
          },
          stats = {
            "Spell hit to 16% (202 rating; Suppression only covers Affliction spells)",
            "Shadow spell damage",
            "Spell haste",
            "Spell crit",
            "Intellect",
            "Stamina (Life Tap fuel)",
          },
          notes = "The 41/0/20 Unstable Affliction raid standard. Keep UA, Corruption, Siphon Life and your assigned curse rolling (Malediction upgrades Curse of Shadow), fill with Shadow Bolt, and chain Life Tap into Dark Pact for mana. Flex: Grim Reach and Nightfall can move to Amplify Curse or Fel Concentration." },
        { key = "DEMONOLOGY", name = "Demonology", role = "CASTER",
          points = {
            [2] = {
                ["Improved Imp"] = 3,
                ["Demonic Embrace"] = 5,
                ["Fel Intellect"] = 3,
                ["Fel Domination"] = 1,
                ["Fel Stamina"] = 3,
                ["Demonic Aegis"] = 3,
                ["Master Summoner"] = 2,
                ["Unholy Power"] = 5,
                ["Demonic Sacrifice"] = 1,
                ["Mana Feed"] = 1,
                ["Master Demonologist"] = 5,
                ["Demonic Knowledge"] = 3,
                ["Demonic Tactics"] = 5,
                ["Summon Felguard"] = 1,
            },
            [3] = {
                ["Improved Shadow Bolt"] = 5,
                ["Cataclysm"] = 5,
                ["Bane"] = 5,
                ["Devastation"] = 5,
            },
          },
          stats = {
            "Spell hit to 16% (202 rating)",
            "Shadow spell damage",
            "Stamina (feeds Demonic Knowledge)",
            "Spell crit",
            "Spell haste",
            "Intellect",
          },
          notes = "The 0/41/20 Felguard raid standard of the Demonic Knowledge and Demonic Tactics era: keep the Felguard out and attacking, spam Shadow Bolt, and let Mana Feed refund the pet through Life Tap. The older Demonic Sacrifice/Ruin 0/21/40 remains the petless alternative. Flex: the Demonic Sacrifice and Mana Feed points." },
        { key = "DESTRUCTION", name = "Destruction", role = "CASTER",
          points = {
            [2] = {
                ["Improved Imp"] = 3,
                ["Demonic Embrace"] = 5,
                ["Fel Intellect"] = 3,
                ["Fel Domination"] = 1,
                ["Fel Stamina"] = 3,
                ["Demonic Aegis"] = 3,
                ["Master Summoner"] = 2,
                ["Demonic Sacrifice"] = 1,
            },
            [3] = {
                ["Cataclysm"] = 5,
                ["Bane"] = 5,
                ["Devastation"] = 5,
                ["Shadowburn"] = 1,
                ["Intensity"] = 2,
                ["Destructive Reach"] = 2,
                ["Improved Immolate"] = 5,
                ["Ruin"] = 1,
                ["Emberstorm"] = 5,
                ["Backlash"] = 3,
                ["Soul Leech"] = 1,
                ["Shadow and Flame"] = 5,
            },
          },
          stats = {
            "Spell hit to 16% (202 rating)",
            "Fire spell damage",
            "Spell crit",
            "Spell haste",
            "Intellect",
            "Stamina",
          },
          notes = "The 0/21/40 fire Destruction build of the Shadow and Flame era: sacrifice the Imp for 15% Fire damage, keep Immolate rolling and spam Incinerate, with Ruin and Devastation turning crits into the payoff. Fel Domination plus Master Summoner re-sacrifices instantly after a battle rez. Flex: Soul Leech, Backlash and Shadowburn points; Conflagrate is the dungeon and PvP pickup." },
    },
}
