-- Commander_Talents — HUNTER talent data (GENERATED 2026-08-04).
-- TBC 2.4.3 final talent state. Regenerate via an agent pass against
-- prompts/commander-talents.md; after any hand-edit, re-run
-- Harness/validate_class_data.lua.

CommanderTalentsData.Classes.HUNTER = {
    trees = {
        {
            name = "Beast Mastery", bg = "HunterBeastMastery",
            talents = {
                { name = "Improved Aspect of the Hawk", icon = "spell_nature_ravenform", row = 1, col = 2, max = 5,
                  ranks = {
                    "While Aspect of the Hawk is active, all normal ranged attacks have a 10% chance of increasing ranged attack speed by 3% for 12 sec.",
                    "While Aspect of the Hawk is active, all normal ranged attacks have a 10% chance of increasing ranged attack speed by 6% for 12 sec.",
                    "While Aspect of the Hawk is active, all normal ranged attacks have a 10% chance of increasing ranged attack speed by 9% for 12 sec.",
                    "While Aspect of the Hawk is active, all normal ranged attacks have a 10% chance of increasing ranged attack speed by 12% for 12 sec.",
                    "While Aspect of the Hawk is active, all normal ranged attacks have a 10% chance of increasing ranged attack speed by 15% for 12 sec.",
                  } },
                { name = "Endurance Training", icon = "spell_nature_reincarnation", row = 1, col = 3, max = 5,
                  ranks = {
                    "Increases the Health of your pet by 2% and your total health by 1%.",
                    "Increases the Health of your pet by 4% and your total health by 2%.",
                    "Increases the Health of your pet by 6% and your total health by 3%.",
                    "Increases the Health of your pet by 8% and your total health by 4%.",
                    "Increases the Health of your pet by 10% and your total health by 5%.",
                  } },
                { name = "Focused Fire", icon = "ability_hunter_silenthunter", row = 2, col = 1, max = 2,
                  ranks = {
                    "All damage caused by you is increased by 1% while your pet is active and the critical strike chance of your Kill Command ability is increased by 10%.",
                    "All damage caused by you is increased by 2% while your pet is active and the critical strike chance of your Kill Command ability is increased by 20%.",
                  } },
                { name = "Improved Aspect of the Monkey", icon = "ability_hunter_aspectofthemonkey", row = 2, col = 2, max = 3,
                  ranks = {
                    "Increases the Dodge bonus of your Aspect of the Monkey by 2%.",
                    "Increases the Dodge bonus of your Aspect of the Monkey by 4%.",
                    "Increases the Dodge bonus of your Aspect of the Monkey by 6%.",
                  } },
                { name = "Thick Hide", icon = "inv_misc_pelt_bear_03", row = 2, col = 3, max = 3,
                  ranks = {
                    "Increases the armor rating of your pets by 7% and your armor contribution from items by 4%.",
                    "Increases the armor rating of your pets by 14% and your armor contribution from items by 7%.",
                    "Increases the armor rating of your pets by 20% and your armor contribution from items by 10%.",
                  } },
                { name = "Improved Revive Pet", icon = "ability_hunter_beastsoothe", row = 2, col = 4, max = 2,
                  ranks = {
                    "Revive Pet's casting time is reduced by 3 sec, mana cost is reduced by 20%, and increases the health your pet returns with by an additional 15%.",
                    "Revive Pet's casting time is reduced by 6 sec, mana cost is reduced by 40%, and increases the health your pet returns with by an additional 30%.",
                  } },
                { name = "Pathfinding", icon = "ability_mount_jungletiger", row = 3, col = 1, max = 2,
                  ranks = {
                    "Increases the speed bonus of your Aspect of the Cheetah and Aspect of the Pack by 4%.",
                    "Increases the speed bonus of your Aspect of the Cheetah and Aspect of the Pack by 8%.",
                  } },
                { name = "Bestial Swiftness", icon = "ability_druid_dash", row = 3, col = 2, max = 1,
                  ranks = {
                    "Increases the outdoor movement speed of your pets by 30%.",
                  } },
                { name = "Unleashed Fury", icon = "ability_bullrush", row = 3, col = 3, max = 5,
                  ranks = {
                    "Increases the damage done by your pets by 4%.",
                    "Increases the damage done by your pets by 8%.",
                    "Increases the damage done by your pets by 12%.",
                    "Increases the damage done by your pets by 16%.",
                    "Increases the damage done by your pets by 20%.",
                  } },
                { name = "Improved Mend Pet", icon = "ability_hunter_mendpet", row = 4, col = 2, max = 2,
                  ranks = {
                    "Reduces the mana cost of your Mend Pet spell by 10% and gives the Mend Pet spell a 25% chance of cleansing 1 Curse, Disease, Magic or Poison effect from the pet each tick.",
                    "Reduces the mana cost of your Mend Pet spell by 20% and gives the Mend Pet spell a 50% chance of cleansing 1 Curse, Disease, Magic or Poison effect from the pet each tick.",
                  } },
                { name = "Ferocity", icon = "inv_misc_monsterclaw_04", row = 4, col = 3, max = 5,
                  ranks = {
                    "Increases the critical strike chance of your pet by 2%.",
                    "Increases the critical strike chance of your pet by 4%.",
                    "Increases the critical strike chance of your pet by 6%.",
                    "Increases the critical strike chance of your pet by 8%.",
                    "Increases the critical strike chance of your pet by 10%.",
                  } },
                { name = "Spirit Bond", icon = "ability_druid_demoralizingroar", row = 5, col = 1, max = 2,
                  ranks = {
                    "While your pet is active, you and your pet will regenerate 1% of total health every 10 sec.",
                    "While your pet is active, you and your pet will regenerate 2% of total health every 10 sec.",
                  } },
                { name = "Intimidation", icon = "ability_devour", row = 5, col = 2, max = 1,
                  ranks = {
                    "Command your pet to intimidate the target on the next successful melee attack, causing a high amount of threat and stunning the target for 3 sec.",
                  } },
                { name = "Bestial Discipline", icon = "spell_nature_abolishmagic", row = 5, col = 4, max = 2,
                  ranks = {
                    "Increases the Focus regeneration of your pets by 50%.",
                    "Increases the Focus regeneration of your pets by 100%.",
                  } },
                { name = "Animal Handler", icon = "ability_hunter_animalhandler", row = 6, col = 1, max = 2,
                  ranks = {
                    "Increases your speed while mounted by 4% and your pet's chance to hit by 2%. The mounted movement speed increase does not stack with other effects.",
                    "Increases your speed while mounted by 8% and your pet's chance to hit by 4%. The mounted movement speed increase does not stack with other effects.",
                  } },
                { name = "Frenzy", icon = "inv_misc_monsterclaw_03", row = 6, col = 3, max = 5, req = "Ferocity",
                  ranks = {
                    "Gives your pet a 20% chance to gain a 30% attack speed increase for 8 sec after dealing a critical strike.",
                    "Gives your pet a 40% chance to gain a 30% attack speed increase for 8 sec after dealing a critical strike.",
                    "Gives your pet a 60% chance to gain a 30% attack speed increase for 8 sec after dealing a critical strike.",
                    "Gives your pet an 80% chance to gain a 30% attack speed increase for 8 sec after dealing a critical strike.",
                    "Gives your pet a 100% chance to gain a 30% attack speed increase for 8 sec after dealing a critical strike.",
                  } },
                { name = "Ferocious Inspiration", icon = "ability_hunter_ferociousinspiration", row = 7, col = 1, max = 3,
                  ranks = {
                    "When your pet scores a critical hit, all party members have all damage increased by 1% for 10 sec.",
                    "When your pet scores a critical hit, all party members have all damage increased by 2% for 10 sec.",
                    "When your pet scores a critical hit, all party members have all damage increased by 3% for 10 sec.",
                  } },
                { name = "Bestial Wrath", icon = "ability_druid_ferociousbite", row = 7, col = 2, max = 1, req = "Intimidation",
                  ranks = {
                    "Send your pet into a rage causing 50% additional damage for 18 sec. While enraged, the beast does not feel pity or remorse or fear and it cannot be stopped unless killed.",
                  } },
                { name = "Catlike Reflexes", icon = "ability_hunter_catlikereflexes", row = 7, col = 3, max = 3,
                  ranks = {
                    "Increases your chance to dodge by 1% and your pet's chance to dodge by an additional 3%.",
                    "Increases your chance to dodge by 2% and your pet's chance to dodge by an additional 6%.",
                    "Increases your chance to dodge by 3% and your pet's chance to dodge by an additional 9%.",
                  } },
                { name = "Serpent's Swiftness", icon = "ability_hunter_serpentswiftness", row = 8, col = 3, max = 5,
                  ranks = {
                    "Increases ranged combat attack speed by 4% and your pet's melee attack speed by 4%.",
                    "Increases ranged combat attack speed by 8% and your pet's melee attack speed by 8%.",
                    "Increases ranged combat attack speed by 12% and your pet's melee attack speed by 12%.",
                    "Increases ranged combat attack speed by 16% and your pet's melee attack speed by 16%.",
                    "Increases ranged combat attack speed by 20% and your pet's melee attack speed by 20%.",
                  } },
                { name = "The Beast Within", icon = "ability_hunter_beastwithin", row = 9, col = 2, max = 1, req = "Bestial Wrath",
                  ranks = {
                    "When your pet is under the effects of Bestial Wrath, you also go into a rage causing 10% additional damage and reducing mana costs of all spells by 20% for 18 sec. While enraged, you do not feel pity or remorse or fear and you cannot be stopped unless killed.",
                  } },
            },
        },
        {
            name = "Marksmanship", bg = "HunterMarksmanship",
            talents = {
                { name = "Improved Concussive Shot", icon = "spell_frost_stun", row = 1, col = 2, max = 5,
                  ranks = {
                    "Gives your Concussive Shot a 4% chance to stun the target for 3 sec.",
                    "Gives your Concussive Shot an 8% chance to stun the target for 3 sec.",
                    "Gives your Concussive Shot a 12% chance to stun the target for 3 sec.",
                    "Gives your Concussive Shot a 16% chance to stun the target for 3 sec.",
                    "Gives your Concussive Shot a 20% chance to stun the target for 3 sec.",
                  } },
                { name = "Lethal Shots", icon = "ability_searingarrow", row = 1, col = 3, max = 5,
                  ranks = {
                    "Increases your critical strike chance with ranged weapons by 1%.",
                    "Increases your critical strike chance with ranged weapons by 2%.",
                    "Increases your critical strike chance with ranged weapons by 3%.",
                    "Increases your critical strike chance with ranged weapons by 4%.",
                    "Increases your critical strike chance with ranged weapons by 5%.",
                  } },
                { name = "Improved Hunter's Mark", icon = "ability_hunter_snipershot", row = 2, col = 2, max = 5,
                  ranks = {
                    "Causes 20% of your Hunter's Mark ability's base attack power to apply to melee attack power as well.",
                    "Causes 40% of your Hunter's Mark ability's base attack power to apply to melee attack power as well.",
                    "Causes 60% of your Hunter's Mark ability's base attack power to apply to melee attack power as well.",
                    "Causes 80% of your Hunter's Mark ability's base attack power to apply to melee attack power as well.",
                    "Causes 100% of your Hunter's Mark ability's base attack power to apply to melee attack power as well.",
                  } },
                { name = "Efficiency", icon = "spell_frost_wizardmark", row = 2, col = 3, max = 5,
                  ranks = {
                    "Reduces the Mana cost of your Shots and Stings by 2%.",
                    "Reduces the Mana cost of your Shots and Stings by 4%.",
                    "Reduces the Mana cost of your Shots and Stings by 6%.",
                    "Reduces the Mana cost of your Shots and Stings by 8%.",
                    "Reduces the Mana cost of your Shots and Stings by 10%.",
                  } },
                { name = "Go for the Throat", icon = "ability_hunter_goforthethroat", row = 3, col = 1, max = 2,
                  ranks = {
                    "Your ranged critical hits cause your pet to generate 25 Focus.",
                    "Your ranged critical hits cause your pet to generate 50 Focus.",
                  } },
                { name = "Improved Arcane Shot", icon = "ability_impalingbolt", row = 3, col = 2, max = 5,
                  ranks = {
                    "Reduces the cooldown of your Arcane Shot by 0.2 sec.",
                    "Reduces the cooldown of your Arcane Shot by 0.4 sec.",
                    "Reduces the cooldown of your Arcane Shot by 0.6 sec.",
                    "Reduces the cooldown of your Arcane Shot by 0.8 sec.",
                    "Reduces the cooldown of your Arcane Shot by 1 sec.",
                  } },
                { name = "Aimed Shot", icon = "inv_spear_07", row = 3, col = 3, max = 1,
                  ranks = {
                    "An aimed shot that increases ranged damage by 70 and reduces healing done to that target by 50%. Lasts 10 sec.",
                  } },
                { name = "Rapid Killing", icon = "ability_hunter_rapidkilling", row = 3, col = 4, max = 2,
                  ranks = {
                    "Reduces the cooldown of your Rapid Fire ability by 1 min. In addition, after killing an opponent that yields experience or honor, your next Aimed Shot, Arcane Shot or Auto Shot causes 10% additional damage. Lasts 20 sec.",
                    "Reduces the cooldown of your Rapid Fire ability by 2 min. In addition, after killing an opponent that yields experience or honor, your next Aimed Shot, Arcane Shot or Auto Shot causes 20% additional damage. Lasts 20 sec.",
                  } },
                { name = "Improved Stings", icon = "ability_hunter_quickshot", row = 4, col = 2, max = 5,
                  ranks = {
                    "Increases the damage done by your Serpent Sting and Wyvern Sting by 6% and the mana drained by your Viper Sting by 6%. In addition, reduces the chance your Stings will be dispelled by 6%.",
                    "Increases the damage done by your Serpent Sting and Wyvern Sting by 12% and the mana drained by your Viper Sting by 12%. In addition, reduces the chance your Stings will be dispelled by 12%.",
                    "Increases the damage done by your Serpent Sting and Wyvern Sting by 18% and the mana drained by your Viper Sting by 18%. In addition, reduces the chance your Stings will be dispelled by 18%.",
                    "Increases the damage done by your Serpent Sting and Wyvern Sting by 24% and the mana drained by your Viper Sting by 24%. In addition, reduces the chance your Stings will be dispelled by 24%.",
                    "Increases the damage done by your Serpent Sting and Wyvern Sting by 30% and the mana drained by your Viper Sting by 30%. In addition, reduces the chance your Stings will be dispelled by 30%.",
                  } },
                { name = "Mortal Shots", icon = "ability_piercedamage", row = 4, col = 3, max = 5, req = "Aimed Shot",
                  ranks = {
                    "Increases your ranged weapon critical strike damage bonus by 6%.",
                    "Increases your ranged weapon critical strike damage bonus by 12%.",
                    "Increases your ranged weapon critical strike damage bonus by 18%.",
                    "Increases your ranged weapon critical strike damage bonus by 24%.",
                    "Increases your ranged weapon critical strike damage bonus by 30%.",
                  } },
                { name = "Concussive Barrage", icon = "spell_arcane_starfire", row = 5, col = 1, max = 3,
                  ranks = {
                    "Your successful Auto Shot attacks have a 2% chance to Daze the target for 4 sec.",
                    "Your successful Auto Shot attacks have a 4% chance to Daze the target for 4 sec.",
                    "Your successful Auto Shot attacks have a 6% chance to Daze the target for 4 sec.",
                  } },
                { name = "Scatter Shot", icon = "ability_golemstormbolt", row = 5, col = 2, max = 1,
                  ranks = {
                    "A short-range shot that deals 50% weapon damage and disorients the target for 4 sec. Any damage caused will remove the effect. Turns off your attack when used.",
                  } },
                { name = "Barrage", icon = "ability_upgrademoonglaive", row = 5, col = 3, max = 3,
                  ranks = {
                    "Increases the damage done by your Multi-Shot and Volley spells by 4%.",
                    "Increases the damage done by your Multi-Shot and Volley spells by 8%.",
                    "Increases the damage done by your Multi-Shot and Volley spells by 12%.",
                  } },
                { name = "Combat Experience", icon = "ability_hunter_combatexperience", row = 6, col = 1, max = 2,
                  ranks = {
                    "Increases your total Agility by 1% and your total Intellect by 3%.",
                    "Increases your total Agility by 2% and your total Intellect by 6%.",
                  } },
                { name = "Ranged Weapon Specialization", icon = "inv_weapon_rifle_06", row = 6, col = 4, max = 5,
                  ranks = {
                    "Increases the damage you deal with ranged weapons by 1%.",
                    "Increases the damage you deal with ranged weapons by 2%.",
                    "Increases the damage you deal with ranged weapons by 3%.",
                    "Increases the damage you deal with ranged weapons by 4%.",
                    "Increases the damage you deal with ranged weapons by 5%.",
                  } },
                { name = "Careful Aim", icon = "ability_hunter_zenarchery", row = 7, col = 1, max = 3,
                  ranks = {
                    "Increases your ranged attack power by an amount equal to 15% of your total Intellect.",
                    "Increases your ranged attack power by an amount equal to 30% of your total Intellect.",
                    "Increases your ranged attack power by an amount equal to 45% of your total Intellect.",
                  } },
                { name = "Trueshot Aura", icon = "ability_trueshot", row = 7, col = 2, max = 1, req = "Scatter Shot",
                  ranks = {
                    "Increases the attack power of party members within 45 yards by 50. Lasts until cancelled.",
                  } },
                { name = "Improved Barrage", icon = "ability_upgrademoonglaive", row = 7, col = 3, max = 3,
                  ranks = {
                    "Increases the critical strike chance of your Multi-Shot ability by 4% and gives you a 33% chance to avoid interruption caused by damage while channeling Volley.",
                    "Increases the critical strike chance of your Multi-Shot ability by 8% and gives you a 66% chance to avoid interruption caused by damage while channeling Volley.",
                    "Increases the critical strike chance of your Multi-Shot ability by 12% and gives you a 100% chance to avoid interruption caused by damage while channeling Volley.",
                  } },
                { name = "Master Marksman", icon = "ability_hunter_mastermarksman", row = 8, col = 2, max = 5,
                  ranks = {
                    "Increases your ranged attack power by 2%.",
                    "Increases your ranged attack power by 4%.",
                    "Increases your ranged attack power by 6%.",
                    "Increases your ranged attack power by 8%.",
                    "Increases your ranged attack power by 10%.",
                  } },
                { name = "Silencing Shot", icon = "ability_theblackarrow", row = 9, col = 2, max = 1, req = "Master Marksman",
                  ranks = {
                    "A shot that deals 50% weapon damage and Silences the target for 3 sec.",
                  } },
            },
        },
        {
            name = "Survival", bg = "HunterSurvival",
            talents = {
                { name = "Monster Slaying", icon = "inv_misc_head_dragon_black", row = 1, col = 1, max = 3,
                  ranks = {
                    "Increases all damage caused against Beasts, Giants and Dragonkin targets by 1% and increases critical damage caused against Beasts, Giants and Dragonkin targets by an additional 1%.",
                    "Increases all damage caused against Beasts, Giants and Dragonkin targets by 2% and increases critical damage caused against Beasts, Giants and Dragonkin targets by an additional 2%.",
                    "Increases all damage caused against Beasts, Giants and Dragonkin targets by 3% and increases critical damage caused against Beasts, Giants and Dragonkin targets by an additional 3%.",
                  } },
                { name = "Humanoid Slaying", icon = "spell_holy_prayerofhealing", row = 1, col = 2, max = 3,
                  ranks = {
                    "Increases all damage caused against Humanoid targets by 1% and increases critical damage caused against Humanoid targets by an additional 1%.",
                    "Increases all damage caused against Humanoid targets by 2% and increases critical damage caused against Humanoid targets by an additional 2%.",
                    "Increases all damage caused against Humanoid targets by 3% and increases critical damage caused against Humanoid targets by an additional 3%.",
                  } },
                { name = "Hawk Eye", icon = "ability_townwatch", row = 1, col = 3, max = 3,
                  ranks = {
                    "Increases the range of your ranged weapons by 2 yards.",
                    "Increases the range of your ranged weapons by 4 yards.",
                    "Increases the range of your ranged weapons by 6 yards.",
                  } },
                { name = "Savage Strikes", icon = "ability_racial_bloodrage", row = 1, col = 4, max = 2,
                  ranks = {
                    "Increases the critical strike chance of Raptor Strike and Mongoose Bite by 10%.",
                    "Increases the critical strike chance of Raptor Strike and Mongoose Bite by 20%.",
                  } },
                { name = "Entrapment", icon = "spell_nature_stranglevines", row = 2, col = 1, max = 3,
                  ranks = {
                    "Gives your Immolation Trap, Frost Trap, Explosive Trap, and Snake Trap an 8% chance to entrap the target, preventing them from moving for 4 sec.",
                    "Gives your Immolation Trap, Frost Trap, Explosive Trap, and Snake Trap a 16% chance to entrap the target, preventing them from moving for 4 sec.",
                    "Gives your Immolation Trap, Frost Trap, Explosive Trap, and Snake Trap a 25% chance to entrap the target, preventing them from moving for 4 sec.",
                  } },
                { name = "Deflection", icon = "ability_parry", row = 2, col = 2, max = 5,
                  ranks = {
                    "Increases your Parry chance by 1%.",
                    "Increases your Parry chance by 2%.",
                    "Increases your Parry chance by 3%.",
                    "Increases your Parry chance by 4%.",
                    "Increases your Parry chance by 5%.",
                  } },
                { name = "Improved Wing Clip", icon = "ability_rogue_trip", row = 2, col = 3, max = 3,
                  ranks = {
                    "Gives your Wing Clip ability a 7% chance to immobilize the target for 5 sec.",
                    "Gives your Wing Clip ability a 14% chance to immobilize the target for 5 sec.",
                    "Gives your Wing Clip ability a 20% chance to immobilize the target for 5 sec.",
                  } },
                { name = "Clever Traps", icon = "spell_nature_timestop", row = 3, col = 1, max = 2,
                  ranks = {
                    "Increases the duration of Freezing and Frost Trap effects by 15%, the damage of Immolation and Explosive Trap effects by 15%, and the number of snakes summoned from Snake Traps by 15%.",
                    "Increases the duration of Freezing and Frost Trap effects by 30%, the damage of Immolation and Explosive Trap effects by 30%, and the number of snakes summoned from Snake Traps by 30%.",
                  } },
                { name = "Survivalist", icon = "spell_shadow_twilight", row = 3, col = 2, max = 5,
                  ranks = {
                    "Increases total health by 2%.",
                    "Increases total health by 4%.",
                    "Increases total health by 6%.",
                    "Increases total health by 8%.",
                    "Increases total health by 10%.",
                  } },
                { name = "Deterrence", icon = "ability_whirlwind", row = 3, col = 3, max = 1,
                  ranks = {
                    "When activated, increases your Dodge and Parry chance by 25% for 10 sec.",
                  } },
                { name = "Trap Mastery", icon = "ability_ensnare", row = 4, col = 1, max = 2,
                  ranks = {
                    "Decreases the chance enemies will resist trap effects by 5%.",
                    "Decreases the chance enemies will resist trap effects by 10%.",
                  } },
                { name = "Surefooted", icon = "ability_kick", row = 4, col = 2, max = 3,
                  ranks = {
                    "Increases hit chance by 1% and increases the chance movement impairing effects will be resisted by an additional 5%.",
                    "Increases hit chance by 2% and increases the chance movement impairing effects will be resisted by an additional 10%.",
                    "Increases hit chance by 3% and increases the chance movement impairing effects will be resisted by an additional 15%.",
                  } },
                { name = "Improved Feign Death", icon = "ability_rogue_feigndeath", row = 4, col = 4, max = 2,
                  ranks = {
                    "Reduces the chance your Feign Death ability will be resisted by 2%.",
                    "Reduces the chance your Feign Death ability will be resisted by 4%.",
                  } },
                { name = "Survival Instincts", icon = "ability_hunter_survivalinstincts", row = 5, col = 1, max = 2,
                  ranks = {
                    "Reduces all damage taken by 2% and increases attack power by 2%.",
                    "Reduces all damage taken by 4% and increases attack power by 4%.",
                  } },
                { name = "Killer Instinct", icon = "spell_holy_blessingofstamina", row = 5, col = 2, max = 3,
                  ranks = {
                    "Increases your critical strike chance with all attacks by 1%.",
                    "Increases your critical strike chance with all attacks by 2%.",
                    "Increases your critical strike chance with all attacks by 3%.",
                  } },
                { name = "Counterattack", icon = "ability_warrior_challange", row = 5, col = 3, max = 1, req = "Deterrence",
                  ranks = {
                    "A strike that becomes active after parrying an opponent's attack. This attack deals 40 damage and immobilizes the target for 5 sec. Counterattack cannot be blocked, dodged, or parried.",
                  } },
                { name = "Resourcefulness", icon = "ability_hunter_resourcefulness", row = 6, col = 1, max = 3,
                  ranks = {
                    "Reduces the mana cost of all traps and melee abilities by 20% and reduces the cooldown of all traps by 2 sec.",
                    "Reduces the mana cost of all traps and melee abilities by 40% and reduces the cooldown of all traps by 4 sec.",
                    "Reduces the mana cost of all traps and melee abilities by 60% and reduces the cooldown of all traps by 6 sec.",
                  } },
                { name = "Lightning Reflexes", icon = "spell_nature_invisibilty", row = 6, col = 3, max = 5,
                  ranks = {
                    "Increases your Agility by 3%.",
                    "Increases your Agility by 6%.",
                    "Increases your Agility by 9%.",
                    "Increases your Agility by 12%.",
                    "Increases your Agility by 15%.",
                  } },
                { name = "Thrill of the Hunt", icon = "ability_hunter_thrillofthehunt", row = 7, col = 1, max = 3,
                  ranks = {
                    "Gives you a 33% chance to regain 40% of the mana cost of any shot when it critically hits.",
                    "Gives you a 66% chance to regain 40% of the mana cost of any shot when it critically hits.",
                    "Gives you a 100% chance to regain 40% of the mana cost of any shot when it critically hits.",
                  } },
                { name = "Wyvern Sting", icon = "inv_spear_02", row = 7, col = 2, max = 1, req = "Killer Instinct",
                  ranks = {
                    "A stinging shot that puts the target to sleep for 12 sec. Any damage will cancel the effect. When the target wakes up, the Sting causes 300 Nature damage over 12 sec. Only one Sting per Hunter can be active on the target at a time.",
                  } },
                { name = "Expose Weakness", icon = "ability_rogue_findweakness", row = 7, col = 3, max = 3, req = "Lightning Reflexes",
                  ranks = {
                    "Your ranged criticals have a 33% chance to apply an Expose Weakness effect to the target. Expose Weakness increases the attack power of all attackers against that target by 25% of your Agility for 7 sec.",
                    "Your ranged criticals have a 66% chance to apply an Expose Weakness effect to the target. Expose Weakness increases the attack power of all attackers against that target by 25% of your Agility for 7 sec.",
                    "Your ranged criticals have a 100% chance to apply an Expose Weakness effect to the target. Expose Weakness increases the attack power of all attackers against that target by 25% of your Agility for 7 sec.",
                  } },
                { name = "Master Tactician", icon = "ability_hunter_mastertactitian", row = 8, col = 2, max = 5,
                  ranks = {
                    "Your successful ranged attacks have a 6% chance to increase your critical strike chance with all attacks by 2% for 8 sec.",
                    "Your successful ranged attacks have a 6% chance to increase your critical strike chance with all attacks by 4% for 8 sec.",
                    "Your successful ranged attacks have a 6% chance to increase your critical strike chance with all attacks by 6% for 8 sec.",
                    "Your successful ranged attacks have a 6% chance to increase your critical strike chance with all attacks by 8% for 8 sec.",
                    "Your successful ranged attacks have a 6% chance to increase your critical strike chance with all attacks by 10% for 8 sec.",
                  } },
                { name = "Readiness", icon = "ability_hunter_readiness", row = 9, col = 2, max = 1, req = "Master Tactician",
                  ranks = {
                    "When activated, this ability immediately finishes the cooldown on your other Hunter abilities.",
                  } },
            },
        },
    },
    builds = {
        { key = "BEAST_MASTERY", name = "Beast Mastery", role = "RANGED",
          points = {
            [1] = {
                ["Improved Aspect of the Hawk"] = 5,
                ["Endurance Training"] = 1,
                ["Focused Fire"] = 2,
                ["Improved Revive Pet"] = 2,
                ["Bestial Swiftness"] = 1,
                ["Unleashed Fury"] = 5,
                ["Improved Mend Pet"] = 1,
                ["Ferocity"] = 5,
                ["Intimidation"] = 1,
                ["Bestial Discipline"] = 2,
                ["Animal Handler"] = 2,
                ["Frenzy"] = 4,
                ["Ferocious Inspiration"] = 3,
                ["Bestial Wrath"] = 1,
                ["Serpent's Swiftness"] = 5,
                ["The Beast Within"] = 1,
            },
            [2] = {
                ["Lethal Shots"] = 5,
                ["Efficiency"] = 5,
                ["Go for the Throat"] = 2,
                ["Aimed Shot"] = 1,
                ["Rapid Killing"] = 2,
                ["Mortal Shots"] = 5,
            },
          },
          stats = {
            "Ranged hit to 9% (142 rating)",
            "Agility",
            "Ranged attack power",
            "Critical strike rating",
            "Haste rating",
            "Intellect",
          },
          notes = "The famous 41/20/0. Serpent's Swiftness and The Beast Within carry roughly a third of your damage through the pet: keep Kill Command and Bestial Wrath on cooldown and weave Steady Shot between autos without clipping them. Frenzy stays at 4/5 because pet crit keeps it rolling; the 1-point fillers (Endurance Training, Bestial Swiftness, Improved Mend Pet) are the flex points." },
        { key = "MARKSMANSHIP", name = "Marksmanship", role = "RANGED",
          points = {
            [1] = {
                ["Improved Aspect of the Hawk"] = 5,
                ["Endurance Training"] = 1,
                ["Focused Fire"] = 2,
                ["Improved Revive Pet"] = 2,
                ["Unleashed Fury"] = 5,
                ["Ferocity"] = 2,
            },
            [2] = {
                ["Lethal Shots"] = 5,
                ["Improved Hunter's Mark"] = 5,
                ["Efficiency"] = 1,
                ["Go for the Throat"] = 2,
                ["Aimed Shot"] = 1,
                ["Rapid Killing"] = 2,
                ["Mortal Shots"] = 5,
                ["Scatter Shot"] = 1,
                ["Barrage"] = 3,
                ["Combat Experience"] = 2,
                ["Ranged Weapon Specialization"] = 5,
                ["Careful Aim"] = 3,
                ["Trueshot Aura"] = 1,
                ["Improved Barrage"] = 3,
                ["Master Marksman"] = 5,
            },
          },
          stats = {
            "Ranged hit to 9% (142 rating)",
            "Agility",
            "Ranged attack power",
            "Intellect (Careful Aim conversion)",
            "Critical strike rating",
            "Haste rating",
          },
          notes = "The 17/44/0 raid Marksman: Trueshot Aura and 5/5 Improved Hunter's Mark buff every physical player in the group while Careful Aim and Master Marksman inflate your own attack power. Scatter Shot is the mandatory stepping stone to Trueshot Aura; the BM sub adds Focused Fire and full Unleashed Fury for the pet. Swap a filler point into Silencing Shot territory only for PvP." },
        { key = "SURVIVAL", name = "Survival", role = "RANGED",
          points = {
            [1] = {
                ["Improved Aspect of the Hawk"] = 5,
                ["Focused Fire"] = 2,
            },
            [2] = {
                ["Lethal Shots"] = 5,
                ["Improved Hunter's Mark"] = 5,
                ["Go for the Throat"] = 2,
                ["Aimed Shot"] = 1,
                ["Rapid Killing"] = 2,
                ["Mortal Shots"] = 5,
            },
            [3] = {
                ["Monster Slaying"] = 3,
                ["Humanoid Slaying"] = 3,
                ["Hawk Eye"] = 3,
                ["Savage Strikes"] = 2,
                ["Clever Traps"] = 2,
                ["Survivalist"] = 2,
                ["Surefooted"] = 3,
                ["Improved Feign Death"] = 2,
                ["Survival Instincts"] = 2,
                ["Killer Instinct"] = 3,
                ["Lightning Reflexes"] = 5,
                ["Thrill of the Hunt"] = 1,
                ["Expose Weakness"] = 3,
            },
          },
          stats = {
            "Ranged hit to 9% (142 rating)",
            "Agility (feeds Expose Weakness)",
            "Critical strike rating",
            "Ranged attack power",
            "Haste rating",
          },
          notes = "The 7/20/34 raid Survival build is a utility spec: 3/3 Expose Weakness turns your ranged crits into 25% of your Agility as attack power for every attacker on the target, so stack Agility past everything else. Improved Hunter's Mark and the Mortal Shots sub keep personal damage respectable. Thrill of the Hunt and Survivalist points are flex; going deeper for Master Tactician and Readiness trades raid value for personal output." },
    },
}
