-- Commander_Talents — MAGE talent data (GENERATED 2026-08-04).
-- TBC 2.4.3 final talent state. Regenerate via an agent pass against
-- prompts/commander-talents.md; after any hand-edit, re-run
-- Harness/validate_class_data.lua.

CommanderTalentsData.Classes.MAGE = {
    trees = {
        {
            name = "Arcane", bg = "MageArcane",
            talents = {
                { name = "Arcane Subtlety", icon = "spell_holy_dispelmagic", row = 1, col = 1, max = 2,
                  ranks = {
                      "Reduces your target's resistance to all your spells by 5 and reduces the threat caused by your Arcane spells by 20%.",
                      "Reduces your target's resistance to all your spells by 10 and reduces the threat caused by your Arcane spells by 40%.",
                  } },
                { name = "Arcane Focus", icon = "spell_holy_devotion", row = 1, col = 2, max = 5,
                  ranks = {
                      "Reduces the chance that the opponent can resist your Arcane spells by 2%.",
                      "Reduces the chance that the opponent can resist your Arcane spells by 4%.",
                      "Reduces the chance that the opponent can resist your Arcane spells by 6%.",
                      "Reduces the chance that the opponent can resist your Arcane spells by 8%.",
                      "Reduces the chance that the opponent can resist your Arcane spells by 10%.",
                  } },
                { name = "Improved Arcane Missiles", icon = "spell_nature_starfall", row = 1, col = 3, max = 5,
                  ranks = {
                      "Gives you a 20% chance to avoid interruption caused by damage while channeling Arcane Missiles.",
                      "Gives you a 40% chance to avoid interruption caused by damage while channeling Arcane Missiles.",
                      "Gives you a 60% chance to avoid interruption caused by damage while channeling Arcane Missiles.",
                      "Gives you an 80% chance to avoid interruption caused by damage while channeling Arcane Missiles.",
                      "Gives you a 100% chance to avoid interruption caused by damage while channeling Arcane Missiles.",
                  } },
                { name = "Wand Specialization", icon = "inv_wand_01", row = 2, col = 1, max = 2,
                  ranks = {
                      "Increases your damage with Wands by 13%.",
                      "Increases your damage with Wands by 25%.",
                  } },
                { name = "Magic Absorption", icon = "spell_nature_astralrecalgroup", row = 2, col = 2, max = 5,
                  ranks = {
                      "Increases all resistances by 2 and causes all spells you fully resist to restore 1% of your total mana.",
                      "Increases all resistances by 4 and causes all spells you fully resist to restore 2% of your total mana.",
                      "Increases all resistances by 6 and causes all spells you fully resist to restore 3% of your total mana.",
                      "Increases all resistances by 8 and causes all spells you fully resist to restore 4% of your total mana.",
                      "Increases all resistances by 10 and causes all spells you fully resist to restore 5% of your total mana.",
                  } },
                { name = "Arcane Concentration", icon = "spell_shadow_manaburn", row = 2, col = 3, max = 5,
                  ranks = {
                      "Gives you a 2% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.",
                      "Gives you a 4% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.",
                      "Gives you a 6% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.",
                      "Gives you an 8% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.",
                      "Gives you a 10% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.",
                  } },
                { name = "Magic Attunement", icon = "spell_nature_abolishmagic", row = 3, col = 1, max = 2,
                  ranks = {
                      "Increases the effect of your Amplify Magic and Dampen Magic spells by 25%.",
                      "Increases the effect of your Amplify Magic and Dampen Magic spells by 50%.",
                  } },
                { name = "Arcane Impact", icon = "spell_nature_wispsplode", row = 3, col = 2, max = 3,
                  ranks = {
                      "Increases the critical strike chance of your Arcane Explosion and Arcane Blast spells by an additional 2%.",
                      "Increases the critical strike chance of your Arcane Explosion and Arcane Blast spells by an additional 4%.",
                      "Increases the critical strike chance of your Arcane Explosion and Arcane Blast spells by an additional 6%.",
                  } },
                { name = "Arcane Fortitude", icon = "spell_arcane_arcaneresilience", row = 3, col = 4, max = 1,
                  ranks = {
                      "Increases your armor by an amount equal to 50% of your Intellect.",
                  } },
                { name = "Improved Mana Shield", icon = "spell_shadow_detectlesserinvisibility", row = 4, col = 1, max = 2,
                  ranks = {
                      "Decreases the mana lost per point of damage taken when Mana Shield is active by 10%.",
                      "Decreases the mana lost per point of damage taken when Mana Shield is active by 20%.",
                  } },
                { name = "Improved Counterspell", icon = "spell_frost_iceshock", row = 4, col = 2, max = 2,
                  ranks = {
                      "Gives your Counterspell a 50% chance to silence the target for 4 sec.",
                      "Gives your Counterspell a 100% chance to silence the target for 4 sec.",
                  } },
                { name = "Arcane Meditation", icon = "spell_shadow_siphonmana", row = 4, col = 4, max = 3,
                  ranks = {
                      "Allows 10% of your mana regeneration to continue while casting.",
                      "Allows 20% of your mana regeneration to continue while casting.",
                      "Allows 30% of your mana regeneration to continue while casting.",
                  } },
                { name = "Improved Blink", icon = "spell_arcane_blink", row = 5, col = 1, max = 2,
                  ranks = {
                      "Reduces the mana cost of your Blink spell by 25%.",
                      "Reduces the mana cost of your Blink spell by 50%.",
                  } },
                { name = "Presence of Mind", icon = "spell_nature_enchantarmor", row = 5, col = 2, max = 1,
                  ranks = {
                      "When activated, your next Mage spell with a casting time less than 10 sec becomes an instant cast spell.",
                  } },
                { name = "Arcane Mind", icon = "spell_shadow_charm", row = 5, col = 4, max = 5,
                  ranks = {
                      "Increases your total Intellect by 3%.",
                      "Increases your total Intellect by 6%.",
                      "Increases your total Intellect by 9%.",
                      "Increases your total Intellect by 12%.",
                      "Increases your total Intellect by 15%.",
                  } },
                { name = "Prismatic Cloak", icon = "spell_arcane_prismaticcloak", row = 6, col = 1, max = 2,
                  ranks = {
                      "Reduces all damage taken by 1%.",
                      "Reduces all damage taken by 2%.",
                  } },
                { name = "Arcane Instability", icon = "spell_shadow_teleport", row = 6, col = 2, max = 3, req = "Presence of Mind",
                  ranks = {
                      "Increases your spell damage and critical strike chance by 1%.",
                      "Increases your spell damage and critical strike chance by 2%.",
                      "Increases your spell damage and critical strike chance by 3%.",
                  } },
                { name = "Arcane Potency", icon = "spell_arcane_arcanepotency", row = 6, col = 3, max = 3, req = "Arcane Concentration",
                  ranks = {
                      "Increases the critical strike chance of any spell cast while Clearcasting by 10%.",
                      "Increases the critical strike chance of any spell cast while Clearcasting by 20%.",
                      "Increases the critical strike chance of any spell cast while Clearcasting by 30%.",
                  } },
                { name = "Empowered Arcane Missiles", icon = "spell_nature_starfall", row = 7, col = 1, max = 3,
                  ranks = {
                      "Your Arcane Missiles spell gains an additional 15% of your bonus spell damage effects, but mana cost is increased by 2%.",
                      "Your Arcane Missiles spell gains an additional 30% of your bonus spell damage effects, but mana cost is increased by 4%.",
                      "Your Arcane Missiles spell gains an additional 45% of your bonus spell damage effects, but mana cost is increased by 6%.",
                  } },
                { name = "Arcane Power", icon = "spell_nature_lightning", row = 7, col = 2, max = 1, req = "Arcane Instability",
                  ranks = {
                      "When activated, your spells deal 30% more damage while costing 30% more mana to cast. This effect lasts 15 sec.",
                  } },
                { name = "Spell Power", icon = "spell_arcane_arcanetorrent", row = 7, col = 3, max = 2,
                  ranks = {
                      "Increases critical strike damage bonus of all spells by 25%.",
                      "Increases critical strike damage bonus of all spells by 50%.",
                  } },
                { name = "Mind Mastery", icon = "spell_arcane_mindmastery", row = 8, col = 2, max = 5,
                  ranks = {
                      "Increases spell damage by up to 5% of your total Intellect.",
                      "Increases spell damage by up to 10% of your total Intellect.",
                      "Increases spell damage by up to 15% of your total Intellect.",
                      "Increases spell damage by up to 20% of your total Intellect.",
                      "Increases spell damage by up to 25% of your total Intellect.",
                  } },
                { name = "Slow", icon = "spell_nature_slow", row = 9, col = 2, max = 1,
                  ranks = {
                      "Reduces target's movement speed by 50%, increases the time between ranged attacks by 50% and increases casting time by 50%. Lasts 15 sec. Slow can only affect one target at a time.",
                  } },
            },
        },
        {
            name = "Fire", bg = "MageFire",
            talents = {
                { name = "Improved Fireball", icon = "spell_fire_fireball02", row = 1, col = 2, max = 5,
                  ranks = {
                      "Reduces the casting time of your Fireball spell by 0.1 sec.",
                      "Reduces the casting time of your Fireball spell by 0.2 sec.",
                      "Reduces the casting time of your Fireball spell by 0.3 sec.",
                      "Reduces the casting time of your Fireball spell by 0.4 sec.",
                      "Reduces the casting time of your Fireball spell by 0.5 sec.",
                  } },
                { name = "Impact", icon = "spell_fire_meteorstorm", row = 1, col = 3, max = 5,
                  ranks = {
                      "Gives your Fire spells a 2% chance to stun the target for 2 sec.",
                      "Gives your Fire spells a 4% chance to stun the target for 2 sec.",
                      "Gives your Fire spells a 6% chance to stun the target for 2 sec.",
                      "Gives your Fire spells an 8% chance to stun the target for 2 sec.",
                      "Gives your Fire spells a 10% chance to stun the target for 2 sec.",
                  } },
                { name = "Ignite", icon = "spell_fire_incinerate", row = 2, col = 1, max = 5,
                  ranks = {
                      "Your critical strikes from Fire damage spells cause the target to burn for an additional 8% of your spell's damage over 4 sec.",
                      "Your critical strikes from Fire damage spells cause the target to burn for an additional 16% of your spell's damage over 4 sec.",
                      "Your critical strikes from Fire damage spells cause the target to burn for an additional 24% of your spell's damage over 4 sec.",
                      "Your critical strikes from Fire damage spells cause the target to burn for an additional 32% of your spell's damage over 4 sec.",
                      "Your critical strikes from Fire damage spells cause the target to burn for an additional 40% of your spell's damage over 4 sec.",
                  } },
                { name = "Flame Throwing", icon = "spell_fire_flare", row = 2, col = 2, max = 2,
                  ranks = {
                      "Increases the range of your Fire spells by 3 yards.",
                      "Increases the range of your Fire spells by 6 yards.",
                  } },
                { name = "Improved Fire Blast", icon = "spell_fire_fireball", row = 2, col = 3, max = 3,
                  ranks = {
                      "Reduces the cooldown of your Fire Blast spell by 0.5 sec.",
                      "Reduces the cooldown of your Fire Blast spell by 1 sec.",
                      "Reduces the cooldown of your Fire Blast spell by 1.5 sec.",
                  } },
                { name = "Incineration", icon = "spell_fire_flameshock", row = 3, col = 1, max = 2,
                  ranks = {
                      "Increases the critical strike chance of your Fire Blast and Scorch spells by 2%.",
                      "Increases the critical strike chance of your Fire Blast and Scorch spells by 4%.",
                  } },
                { name = "Improved Flamestrike", icon = "spell_fire_selfdestruct", row = 3, col = 2, max = 3,
                  ranks = {
                      "Increases the critical strike chance of your Flamestrike spell by 5%.",
                      "Increases the critical strike chance of your Flamestrike spell by 10%.",
                      "Increases the critical strike chance of your Flamestrike spell by 15%.",
                  } },
                { name = "Pyroblast", icon = "spell_fire_fireball02", row = 3, col = 3, max = 1,
                  ranks = {
                      "Hurls an immense fiery boulder that causes 141 to 188 Fire damage and an additional 56 Fire damage over 12 sec.",
                  } },
                { name = "Burning Soul", icon = "spell_fire_fire", row = 3, col = 4, max = 2,
                  ranks = {
                      "Gives your Fire spells a 35% chance to not lose casting time when you take damage and reduces the threat caused by your Fire spells by 5%.",
                      "Gives your Fire spells a 70% chance to not lose casting time when you take damage and reduces the threat caused by your Fire spells by 10%.",
                  } },
                { name = "Improved Scorch", icon = "spell_fire_soulburn", row = 4, col = 1, max = 3,
                  ranks = {
                      "Your Scorch spells have a 33% chance to cause your target to be vulnerable to Fire damage. This vulnerability increases the Fire damage dealt to your target by 3% and lasts 30 sec. Stacks up to 5 times.",
                      "Your Scorch spells have a 66% chance to cause your target to be vulnerable to Fire damage. This vulnerability increases the Fire damage dealt to your target by 3% and lasts 30 sec. Stacks up to 5 times.",
                      "Your Scorch spells have a 100% chance to cause your target to be vulnerable to Fire damage. This vulnerability increases the Fire damage dealt to your target by 3% and lasts 30 sec. Stacks up to 5 times.",
                  } },
                { name = "Molten Shields", icon = "spell_fire_firearmor", row = 4, col = 2, max = 2,
                  ranks = {
                      "Causes your Fire Ward to have a 10% chance to reflect Fire spells while active. In addition, your Molten Armor has a 50% chance to affect ranged and spell attacks.",
                      "Causes your Fire Ward to have a 20% chance to reflect Fire spells while active. In addition, your Molten Armor has a 100% chance to affect ranged and spell attacks.",
                  } },
                { name = "Master of Elements", icon = "spell_fire_masterofelements", row = 4, col = 4, max = 3,
                  ranks = {
                      "Your Fire and Frost spell criticals will refund 10% of their base mana cost.",
                      "Your Fire and Frost spell criticals will refund 20% of their base mana cost.",
                      "Your Fire and Frost spell criticals will refund 30% of their base mana cost.",
                  } },
                { name = "Playing with Fire", icon = "spell_fire_playingwithfire", row = 5, col = 1, max = 3,
                  ranks = {
                      "Increases all spell damage caused by 1% and all spell damage taken by 1%.",
                      "Increases all spell damage caused by 2% and all spell damage taken by 2%.",
                      "Increases all spell damage caused by 3% and all spell damage taken by 3%.",
                  } },
                { name = "Critical Mass", icon = "spell_nature_wispheal", row = 5, col = 2, max = 3,
                  ranks = {
                      "Increases the critical strike chance of your Fire spells by 2%.",
                      "Increases the critical strike chance of your Fire spells by 4%.",
                      "Increases the critical strike chance of your Fire spells by 6%.",
                  } },
                { name = "Blast Wave", icon = "spell_holy_excorcism_02", row = 5, col = 3, max = 1, req = "Pyroblast",
                  ranks = {
                      "A wave of flame radiates outward from the caster, damaging all enemies caught within the blast for 154 to 187 Fire damage, and dazing them for 6 sec.",
                  } },
                { name = "Blazing Speed", icon = "spell_fire_burningspeed", row = 6, col = 1, max = 2,
                  ranks = {
                      "Gives you a 5% chance when hit by a melee or ranged attack to increase your movement speed by 50% and dissipate all movement impairing effects. This effect lasts 8 sec.",
                      "Gives you a 10% chance when hit by a melee or ranged attack to increase your movement speed by 50% and dissipate all movement impairing effects. This effect lasts 8 sec.",
                  } },
                { name = "Fire Power", icon = "spell_fire_immolation", row = 6, col = 3, max = 5,
                  ranks = {
                      "Increases the damage done by your Fire spells by 2%.",
                      "Increases the damage done by your Fire spells by 4%.",
                      "Increases the damage done by your Fire spells by 6%.",
                      "Increases the damage done by your Fire spells by 8%.",
                      "Increases the damage done by your Fire spells by 10%.",
                  } },
                { name = "Pyromaniac", icon = "spell_fire_burnout", row = 7, col = 1, max = 3,
                  ranks = {
                      "Increases chance to critically hit and reduces the mana cost of all Fire spells by an additional 1%.",
                      "Increases chance to critically hit and reduces the mana cost of all Fire spells by an additional 2%.",
                      "Increases chance to critically hit and reduces the mana cost of all Fire spells by an additional 3%.",
                  } },
                { name = "Combustion", icon = "spell_fire_sealoffire", row = 7, col = 2, max = 1, req = "Critical Mass",
                  ranks = {
                      "When activated, this spell causes each of your Fire damage spell hits to increase your critical strike chance with Fire damage spells by 10%. This effect lasts until you have caused 3 critical strikes with Fire spells.",
                  } },
                { name = "Molten Fury", icon = "spell_fire_moltenblood", row = 7, col = 3, max = 2,
                  ranks = {
                      "Increases damage of all spells against targets with less than 20% health by 10%.",
                      "Increases damage of all spells against targets with less than 20% health by 20%.",
                  } },
                { name = "Empowered Fireball", icon = "spell_fire_flamebolt", row = 8, col = 3, max = 5,
                  ranks = {
                      "Your Fireball spell gains an additional 3% of your bonus spell damage effects.",
                      "Your Fireball spell gains an additional 6% of your bonus spell damage effects.",
                      "Your Fireball spell gains an additional 9% of your bonus spell damage effects.",
                      "Your Fireball spell gains an additional 12% of your bonus spell damage effects.",
                      "Your Fireball spell gains an additional 15% of your bonus spell damage effects.",
                  } },
                { name = "Dragon's Breath", icon = "inv_misc_head_dragon_01", row = 9, col = 2, max = 1, req = "Combustion",
                  ranks = {
                      "Targets in a cone in front of the caster take 370 to 430 Fire damage and are Disoriented for 3 sec. Any direct damaging attack will revive targets. Turns off your attack when used.",
                  } },
            },
        },
        {
            name = "Frost", bg = "MageFrost",
            talents = {
                { name = "Frost Warding", icon = "spell_frost_frostward", row = 1, col = 1, max = 2,
                  ranks = {
                      "Increases the armor and resistances given by your Frost Armor and Ice Armor spells by 15%. In addition, gives your Frost Ward a 10% chance to reflect Frost spells and effects while active.",
                      "Increases the armor and resistances given by your Frost Armor and Ice Armor spells by 30%. In addition, gives your Frost Ward a 20% chance to reflect Frost spells and effects while active.",
                  } },
                { name = "Improved Frostbolt", icon = "spell_frost_frostbolt02", row = 1, col = 2, max = 5,
                  ranks = {
                      "Reduces the casting time of your Frostbolt spell by 0.1 sec.",
                      "Reduces the casting time of your Frostbolt spell by 0.2 sec.",
                      "Reduces the casting time of your Frostbolt spell by 0.3 sec.",
                      "Reduces the casting time of your Frostbolt spell by 0.4 sec.",
                      "Reduces the casting time of your Frostbolt spell by 0.5 sec.",
                  } },
                { name = "Elemental Precision", icon = "spell_ice_magicdamage", row = 1, col = 3, max = 3,
                  ranks = {
                      "Reduces the mana cost and chance targets resist your Frost and Fire spells by 1%.",
                      "Reduces the mana cost and chance targets resist your Frost and Fire spells by 2%.",
                      "Reduces the mana cost and chance targets resist your Frost and Fire spells by 3%.",
                  } },
                { name = "Ice Shards", icon = "spell_frost_iceshard", row = 2, col = 1, max = 5,
                  ranks = {
                      "Increases the critical strike damage bonus of your Frost spells by 20%.",
                      "Increases the critical strike damage bonus of your Frost spells by 40%.",
                      "Increases the critical strike damage bonus of your Frost spells by 60%.",
                      "Increases the critical strike damage bonus of your Frost spells by 80%.",
                      "Increases the critical strike damage bonus of your Frost spells by 100%.",
                  } },
                { name = "Frostbite", icon = "spell_frost_frostarmor", row = 2, col = 2, max = 3,
                  ranks = {
                      "Gives your Chill effects a 5% chance to freeze the target for 5 sec.",
                      "Gives your Chill effects a 10% chance to freeze the target for 5 sec.",
                      "Gives your Chill effects a 15% chance to freeze the target for 5 sec.",
                  } },
                { name = "Improved Frost Nova", icon = "spell_frost_freezingbreath", row = 2, col = 3, max = 2,
                  ranks = {
                      "Reduces the cooldown of your Frost Nova spell by 2 sec.",
                      "Reduces the cooldown of your Frost Nova spell by 4 sec.",
                  } },
                { name = "Permafrost", icon = "spell_frost_wisp", row = 2, col = 4, max = 3,
                  ranks = {
                      "Increases the duration of your Chill effects by 1 sec and reduces the target's speed by an additional 4%.",
                      "Increases the duration of your Chill effects by 2 sec and reduces the target's speed by an additional 7%.",
                      "Increases the duration of your Chill effects by 3 sec and reduces the target's speed by an additional 10%.",
                  } },
                { name = "Piercing Ice", icon = "spell_frost_frostbolt", row = 3, col = 1, max = 3,
                  ranks = {
                      "Increases the damage done by your Frost spells by 2%.",
                      "Increases the damage done by your Frost spells by 4%.",
                      "Increases the damage done by your Frost spells by 6%.",
                  } },
                { name = "Icy Veins", icon = "spell_frost_coldhearted", row = 3, col = 2, max = 1,
                  ranks = {
                      "Hastens your spellcasting, increasing spell casting speed by 20% and gives you 100% chance to avoid interruption caused by damage while casting any spell. Lasts 20 sec.",
                  } },
                { name = "Improved Blizzard", icon = "spell_frost_icestorm", row = 3, col = 4, max = 3,
                  ranks = {
                      "Adds a chill effect to your Blizzard spell. This effect lowers the target's movement speed by 30%. Lasts 4 sec.",
                      "Adds a chill effect to your Blizzard spell. This effect lowers the target's movement speed by 50%. Lasts 4 sec.",
                      "Adds a chill effect to your Blizzard spell. This effect lowers the target's movement speed by 65%. Lasts 4 sec.",
                  } },
                { name = "Arctic Reach", icon = "spell_shadow_darkritual", row = 4, col = 1, max = 2,
                  ranks = {
                      "Increases the range of your Frostbolt and Blizzard spells and the radius of your Frost Nova and Cone of Cold spells by 10%.",
                      "Increases the range of your Frostbolt and Blizzard spells and the radius of your Frost Nova and Cone of Cold spells by 20%.",
                  } },
                { name = "Frost Channeling", icon = "spell_frost_stun", row = 4, col = 2, max = 3,
                  ranks = {
                      "Reduces the mana cost of your Frost spells by 5% and reduces the threat caused by your Frost spells by 4%.",
                      "Reduces the mana cost of your Frost spells by 10% and reduces the threat caused by your Frost spells by 7%.",
                      "Reduces the mana cost of your Frost spells by 15% and reduces the threat caused by your Frost spells by 10%.",
                  } },
                { name = "Shatter", icon = "spell_frost_frostshock", row = 4, col = 3, max = 5, req = "Improved Frost Nova",
                  ranks = {
                      "Increases the critical strike chance of all your spells against frozen targets by 10%.",
                      "Increases the critical strike chance of all your spells against frozen targets by 20%.",
                      "Increases the critical strike chance of all your spells against frozen targets by 30%.",
                      "Increases the critical strike chance of all your spells against frozen targets by 40%.",
                      "Increases the critical strike chance of all your spells against frozen targets by 50%.",
                  } },
                { name = "Frozen Core", icon = "spell_frost_frozencore", row = 5, col = 1, max = 3,
                  ranks = {
                      "Reduces the damage taken by Frost and Fire effects by 2%.",
                      "Reduces the damage taken by Frost and Fire effects by 4%.",
                      "Reduces the damage taken by Frost and Fire effects by 6%.",
                  } },
                { name = "Cold Snap", icon = "spell_frost_wizardmark", row = 5, col = 2, max = 1,
                  ranks = {
                      "When activated, this spell finishes the cooldown on all Frost spells you recently cast.",
                  } },
                { name = "Improved Cone of Cold", icon = "spell_frost_glacier", row = 5, col = 3, max = 3,
                  ranks = {
                      "Increases the damage dealt by your Cone of Cold spell by 15%.",
                      "Increases the damage dealt by your Cone of Cold spell by 25%.",
                      "Increases the damage dealt by your Cone of Cold spell by 35%.",
                  } },
                { name = "Ice Floes", icon = "spell_frost_icefloes", row = 6, col = 1, max = 2,
                  ranks = {
                      "Reduces the cooldown of your Cone of Cold, Cold Snap, Ice Barrier and Ice Block spells by 10%.",
                      "Reduces the cooldown of your Cone of Cold, Cold Snap, Ice Barrier and Ice Block spells by 20%.",
                  } },
                { name = "Winter's Chill", icon = "spell_frost_chillingblast", row = 6, col = 3, max = 5,
                  ranks = {
                      "Gives your Frost damage spells a 20% chance to apply the Winter's Chill effect, which increases the chance a Frost spell will critically hit the target by 2% for 15 sec. Stacks up to 5 times.",
                      "Gives your Frost damage spells a 40% chance to apply the Winter's Chill effect, which increases the chance a Frost spell will critically hit the target by 2% for 15 sec. Stacks up to 5 times.",
                      "Gives your Frost damage spells a 60% chance to apply the Winter's Chill effect, which increases the chance a Frost spell will critically hit the target by 2% for 15 sec. Stacks up to 5 times.",
                      "Gives your Frost damage spells an 80% chance to apply the Winter's Chill effect, which increases the chance a Frost spell will critically hit the target by 2% for 15 sec. Stacks up to 5 times.",
                      "Gives your Frost damage spells a 100% chance to apply the Winter's Chill effect, which increases the chance a Frost spell will critically hit the target by 2% for 15 sec. Stacks up to 5 times.",
                  } },
                { name = "Ice Barrier", icon = "spell_ice_lament", row = 7, col = 2, max = 1, req = "Cold Snap",
                  ranks = {
                      "Instantly shields you, absorbing 438 damage. Lasts 1 min. While the shield holds, spells will not be interrupted.",
                  } },
                { name = "Arctic Winds", icon = "spell_frost_arcticwinds", row = 7, col = 3, max = 5,
                  ranks = {
                      "Increases all Frost damage you cause by 1% and reduces the chance melee and ranged attacks will hit you by 1%.",
                      "Increases all Frost damage you cause by 2% and reduces the chance melee and ranged attacks will hit you by 2%.",
                      "Increases all Frost damage you cause by 3% and reduces the chance melee and ranged attacks will hit you by 3%.",
                      "Increases all Frost damage you cause by 4% and reduces the chance melee and ranged attacks will hit you by 4%.",
                      "Increases all Frost damage you cause by 5% and reduces the chance melee and ranged attacks will hit you by 5%.",
                  } },
                { name = "Empowered Frostbolt", icon = "spell_frost_frostbolt02", row = 8, col = 2, max = 5,
                  ranks = {
                      "Your Frostbolt spell gains an additional 2% of your bonus spell damage effects and an additional 1% chance to critically strike.",
                      "Your Frostbolt spell gains an additional 4% of your bonus spell damage effects and an additional 2% chance to critically strike.",
                      "Your Frostbolt spell gains an additional 6% of your bonus spell damage effects and an additional 3% chance to critically strike.",
                      "Your Frostbolt spell gains an additional 8% of your bonus spell damage effects and an additional 4% chance to critically strike.",
                      "Your Frostbolt spell gains an additional 10% of your bonus spell damage effects and an additional 5% chance to critically strike.",
                  } },
                { name = "Summon Water Elemental", icon = "spell_frost_summonwaterelemental_2", row = 9, col = 2, max = 1,
                  ranks = {
                      "Summon a Water Elemental to fight for the caster for 45 sec.",
                  } },
            },
        },
    },
    builds = {
        { key = "ARCANE", name = "Arcane", role = "CASTER",
          points = {
              [1] = {
                  ["Arcane Subtlety"] = 2, ["Arcane Focus"] = 5, ["Magic Absorption"] = 2,
                  ["Arcane Concentration"] = 5, ["Arcane Impact"] = 3, ["Arcane Meditation"] = 3,
                  ["Presence of Mind"] = 1, ["Arcane Mind"] = 5, ["Arcane Instability"] = 3,
                  ["Arcane Potency"] = 3, ["Arcane Power"] = 1, ["Spell Power"] = 2,
                  ["Mind Mastery"] = 5, ["Slow"] = 1,
              },
              [3] = {
                  ["Improved Frostbolt"] = 5, ["Elemental Precision"] = 3, ["Ice Shards"] = 5,
                  ["Piercing Ice"] = 3, ["Icy Veins"] = 1, ["Frost Channeling"] = 3,
              },
          },
          stats = {
              "Spell Hit to 6% for Arcane Blast (76 rating; Arcane Focus covers 10% of the 16% cap)",
              "Spell Hit 13% (164 rating) caps the Frostbolt weave (Elemental Precision covers 3%)",
              "Spell Damage",
              "Intellect (Mind Mastery turns 25% of it into damage)",
              "Spell Crit",
              "Spell Haste",
              "Spirit and mp5",
          },
          notes = "The 40/0/21 family cast as 41/0/20: stack Arcane Blast, weave Frostbolt to recover mana, and run Icy Veins plus Arcane Power on cooldown with Slow as the utility capstone. Drop Slow for Cold Snap (the classic 40/0/21) to double Icy Veins on burn fights; Empowered Arcane Missiles is the other flex if you weave Missiles instead of Frostbolt." },
        { key = "FIRE", name = "Fire", role = "CASTER",
          points = {
              [1] = {
                  ["Arcane Subtlety"] = 2,
              },
              [2] = {
                  ["Improved Fireball"] = 5, ["Ignite"] = 5, ["Flame Throwing"] = 2,
                  ["Improved Fire Blast"] = 1, ["Incineration"] = 2, ["Pyroblast"] = 1,
                  ["Burning Soul"] = 2, ["Improved Scorch"] = 3, ["Master of Elements"] = 3,
                  ["Playing with Fire"] = 3, ["Critical Mass"] = 3, ["Blast Wave"] = 1,
                  ["Fire Power"] = 5, ["Pyromaniac"] = 3, ["Combustion"] = 1,
                  ["Molten Fury"] = 2, ["Empowered Fireball"] = 5, ["Dragon's Breath"] = 1,
              },
              [3] = {
                  ["Improved Frostbolt"] = 5, ["Elemental Precision"] = 3, ["Ice Shards"] = 2,
                  ["Icy Veins"] = 1,
              },
          },
          stats = {
              "Spell Hit to 13% (164 rating; Elemental Precision covers 3% of the 16% cap)",
              "Spell Damage",
              "Spell Crit (feeds Ignite and Master of Elements)",
              "Spell Haste",
              "Intellect",
              "mp5",
          },
          notes = "The 2/48/11 fire raid standard: keep Improved Scorch stacked, spam Fireball, and line up Combustion with Icy Veins for burst, with Molten Fury closing fights hard. Picked over 10/48/3 because Icy Veins out-damages Clearcasting when a shadow priest feeds you mana; swap to the Arcane Concentration variant if mana starved. The Improved Fire Blast point and Blast Wave are the flex picks." },
        { key = "FROST", name = "Frost", role = "CASTER",
          points = {
              [1] = {
                  ["Arcane Subtlety"] = 2, ["Arcane Focus"] = 3, ["Magic Absorption"] = 1,
                  ["Arcane Concentration"] = 5, ["Arcane Impact"] = 3, ["Arcane Fortitude"] = 1,
                  ["Arcane Meditation"] = 3,
              },
              [3] = {
                  ["Improved Frostbolt"] = 5, ["Elemental Precision"] = 3, ["Ice Shards"] = 5,
                  ["Piercing Ice"] = 3, ["Icy Veins"] = 1, ["Arctic Reach"] = 2,
                  ["Frost Channeling"] = 3, ["Cold Snap"] = 1, ["Improved Cone of Cold"] = 2,
                  ["Ice Floes"] = 2, ["Winter's Chill"] = 4, ["Ice Barrier"] = 1,
                  ["Arctic Winds"] = 5, ["Empowered Frostbolt"] = 5,
                  ["Summon Water Elemental"] = 1,
              },
          },
          stats = {
              "Spell Hit to 13% (164 rating; Elemental Precision covers 3% of the 16% cap)",
              "Spell Damage",
              "Spell Crit (Ice Shards doubles the crit payoff)",
              "Spell Haste",
              "Intellect",
              "Spirit and mp5",
          },
          notes = "The community deep frost raid build (18/0/43): Frostbolt spam with Icy Veins, Cold Snap and the Water Elemental stacked into burst windows while Winter's Chill feeds the raid's casters. 4/5 Winter's Chill is deliberate - the fifth point is the flex against Improved Cone of Cold; Shatter and Frostbite are skipped because raid bosses cannot be frozen." },
    },
}
