-- Commander_Talents — ROGUE talent data (GENERATED 2026-08-04).
-- TBC 2.4.3 final talent state. Regenerate via an agent pass against
-- prompts/commander-talents.md; after any hand-edit, re-run
-- Harness/validate_class_data.lua.

CommanderTalentsData.Classes.ROGUE = {
    trees = {
        {
            name = "Assassination", bg = "RogueAssassination",
            talents = {
                { name = "Improved Eviscerate", icon = "ability_rogue_eviscerate", row = 1, col = 1, max = 3,
                  ranks = {
                    "Increases the damage of your Eviscerate ability by 5%.",
                    "Increases the damage of your Eviscerate ability by 10%.",
                    "Increases the damage of your Eviscerate ability by 15%.",
                  } },
                { name = "Remorseless Attacks", icon = "ability_fiegndead", row = 1, col = 2, max = 2,
                  ranks = {
                    "After killing an opponent that yields experience or honor, gives you a 20% increased critical strike chance on your next Sinister Strike, Hemorrhage, Backstab, Mutilate, Ambush, or Ghostly Strike. Lasts 20 sec.",
                    "After killing an opponent that yields experience or honor, gives you a 40% increased critical strike chance on your next Sinister Strike, Hemorrhage, Backstab, Mutilate, Ambush, or Ghostly Strike. Lasts 20 sec.",
                  } },
                { name = "Malice", icon = "ability_racial_bloodrage", row = 1, col = 3, max = 5,
                  ranks = {
                    "Increases your critical strike chance by 1%.",
                    "Increases your critical strike chance by 2%.",
                    "Increases your critical strike chance by 3%.",
                    "Increases your critical strike chance by 4%.",
                    "Increases your critical strike chance by 5%.",
                  } },
                { name = "Ruthlessness", icon = "ability_druid_disembowel", row = 2, col = 1, max = 3,
                  ranks = {
                    "Gives your melee finishing moves a 20% chance to add a combo point to your target.",
                    "Gives your melee finishing moves a 40% chance to add a combo point to your target.",
                    "Gives your melee finishing moves a 60% chance to add a combo point to your target.",
                  } },
                { name = "Murder", icon = "spell_shadow_deathscream", row = 2, col = 2, max = 2,
                  ranks = {
                    "Increases all damage caused against Humanoid, Giant, Beast and Dragonkin targets by 1%.",
                    "Increases all damage caused against Humanoid, Giant, Beast and Dragonkin targets by 2%.",
                  } },
                { name = "Puncturing Wounds", icon = "ability_backstab", row = 2, col = 4, max = 3,
                  ranks = {
                    "Increases the critical strike chance of your Backstab ability by 10%, and the critical strike chance of your Mutilate ability by 5%.",
                    "Increases the critical strike chance of your Backstab ability by 20%, and the critical strike chance of your Mutilate ability by 10%.",
                    "Increases the critical strike chance of your Backstab ability by 30%, and the critical strike chance of your Mutilate ability by 15%.",
                  } },
                { name = "Relentless Strikes", icon = "ability_warrior_decisivestrike", row = 3, col = 1, max = 1,
                  ranks = {
                    "Your finishing moves have a 20% chance per combo point to restore 25 energy.",
                  } },
                { name = "Improved Expose Armor", icon = "ability_warrior_riposte", row = 3, col = 2, max = 2,
                  ranks = {
                    "Increases the armor reduced by your Expose Armor ability by 25%.",
                    "Increases the armor reduced by your Expose Armor ability by 50%.",
                  } },
                { name = "Lethality", icon = "ability_criticalstrike", row = 3, col = 3, max = 5, req = "Malice",
                  ranks = {
                    "Increases the critical strike damage bonus of your Sinister Strike, Gouge, Backstab, Ghostly Strike, Mutilate, Shiv, and Hemorrhage abilities by 6%.",
                    "Increases the critical strike damage bonus of your Sinister Strike, Gouge, Backstab, Ghostly Strike, Mutilate, Shiv, and Hemorrhage abilities by 12%.",
                    "Increases the critical strike damage bonus of your Sinister Strike, Gouge, Backstab, Ghostly Strike, Mutilate, Shiv, and Hemorrhage abilities by 18%.",
                    "Increases the critical strike damage bonus of your Sinister Strike, Gouge, Backstab, Ghostly Strike, Mutilate, Shiv, and Hemorrhage abilities by 24%.",
                    "Increases the critical strike damage bonus of your Sinister Strike, Gouge, Backstab, Ghostly Strike, Mutilate, Shiv, and Hemorrhage abilities by 30%.",
                  } },
                { name = "Vile Poisons", icon = "ability_rogue_feigndeath", row = 4, col = 2, max = 5,
                  ranks = {
                    "Increases the damage dealt by your poisons and Envenom ability by 4% and gives your poisons an additional 8% chance to resist dispel effects.",
                    "Increases the damage dealt by your poisons and Envenom ability by 8% and gives your poisons an additional 16% chance to resist dispel effects.",
                    "Increases the damage dealt by your poisons and Envenom ability by 12% and gives your poisons an additional 24% chance to resist dispel effects.",
                    "Increases the damage dealt by your poisons and Envenom ability by 16% and gives your poisons an additional 32% chance to resist dispel effects.",
                    "Increases the damage dealt by your poisons and Envenom ability by 20% and gives your poisons an additional 40% chance to resist dispel effects.",
                  } },
                { name = "Improved Poisons", icon = "ability_poisons", row = 4, col = 3, max = 5,
                  ranks = {
                    "Increases the chance to apply poisons to your target by 2%.",
                    "Increases the chance to apply poisons to your target by 4%.",
                    "Increases the chance to apply poisons to your target by 6%.",
                    "Increases the chance to apply poisons to your target by 8%.",
                    "Increases the chance to apply poisons to your target by 10%.",
                  } },
                { name = "Fleet Footed", icon = "ability_rogue_fleetfooted", row = 5, col = 1, max = 2,
                  ranks = {
                    "Increases your chance to resist movement impairing effects by 5% and increases your movement speed by 8%. This does not stack with other movement speed increasing effects.",
                    "Increases your chance to resist movement impairing effects by 10% and increases your movement speed by 15%. This does not stack with other movement speed increasing effects.",
                  } },
                { name = "Cold Blood", icon = "spell_ice_lament", row = 5, col = 2, max = 1,
                  ranks = {
                    "When activated, increases the critical strike chance of your next offensive ability by 100%.",
                  } },
                { name = "Improved Kidney Shot", icon = "ability_rogue_kidneyshot", row = 5, col = 3, max = 3,
                  ranks = {
                    "While affected by your Kidney Shot ability, the target receives an additional 3% damage from all sources.",
                    "While affected by your Kidney Shot ability, the target receives an additional 6% damage from all sources.",
                    "While affected by your Kidney Shot ability, the target receives an additional 9% damage from all sources.",
                  } },
                { name = "Quick Recovery", icon = "ability_rogue_quickrecovery", row = 5, col = 4, max = 2,
                  ranks = {
                    "All healing effects on you are increased by 10%. In addition, your finishing moves cost 40% less Energy when they fail to hit.",
                    "All healing effects on you are increased by 20%. In addition, your finishing moves cost 80% less Energy when they fail to hit.",
                  } },
                { name = "Seal Fate", icon = "spell_shadow_chilltouch", row = 6, col = 2, max = 5, req = "Cold Blood",
                  ranks = {
                    "Your critical strikes from abilities that add combo points have a 20% chance to add an additional combo point.",
                    "Your critical strikes from abilities that add combo points have a 40% chance to add an additional combo point.",
                    "Your critical strikes from abilities that add combo points have a 60% chance to add an additional combo point.",
                    "Your critical strikes from abilities that add combo points have an 80% chance to add an additional combo point.",
                    "Your critical strikes from abilities that add combo points have a 100% chance to add an additional combo point.",
                  } },
                { name = "Master Poisoner", icon = "ability_creature_poison_06", row = 6, col = 3, max = 2,
                  ranks = {
                    "Reduces the chance your poisons will be resisted by 5% and increases your chance to resist Poison effects by an additional 15%.",
                    "Reduces the chance your poisons will be resisted by 10% and increases your chance to resist Poison effects by an additional 30%.",
                  } },
                { name = "Vigor", icon = "spell_nature_earthbindtotem", row = 7, col = 2, max = 1,
                  ranks = {
                    "Increases your maximum Energy by 10.",
                  } },
                { name = "Deadened Nerves", icon = "ability_rogue_deadenednerves", row = 7, col = 3, max = 5,
                  ranks = {
                    "Decreases all physical damage taken by 1%.",
                    "Decreases all physical damage taken by 2%.",
                    "Decreases all physical damage taken by 3%.",
                    "Decreases all physical damage taken by 4%.",
                    "Decreases all physical damage taken by 5%.",
                  } },
                { name = "Find Weakness", icon = "ability_rogue_findweakness", row = 8, col = 3, max = 5,
                  ranks = {
                    "Your finishing moves increase the damage of all your offensive abilities by 2% for 10 sec.",
                    "Your finishing moves increase the damage of all your offensive abilities by 4% for 10 sec.",
                    "Your finishing moves increase the damage of all your offensive abilities by 6% for 10 sec.",
                    "Your finishing moves increase the damage of all your offensive abilities by 8% for 10 sec.",
                    "Your finishing moves increase the damage of all your offensive abilities by 10% for 10 sec.",
                  } },
                { name = "Mutilate", icon = "ability_rogue_shadowstrikes", row = 9, col = 2, max = 1, req = "Vigor",
                  ranks = {
                    "Instantly attacks with both weapons for an additional 44 with each weapon. Damage is increased by 50% against Poisoned targets. Must be behind the target. Awards 2 combo points.",
                  } },
            },
        },
        {
            name = "Combat", bg = "RogueCombat",
            talents = {
                { name = "Improved Gouge", icon = "ability_gouge", row = 1, col = 1, max = 3,
                  ranks = {
                    "Increases the effect duration of your Gouge ability by 0.5 sec.",
                    "Increases the effect duration of your Gouge ability by 1 sec.",
                    "Increases the effect duration of your Gouge ability by 1.5 sec.",
                  } },
                { name = "Improved Sinister Strike", icon = "spell_shadow_ritualofsacrifice", row = 1, col = 2, max = 2,
                  ranks = {
                    "Reduces the Energy cost of your Sinister Strike ability by 3.",
                    "Reduces the Energy cost of your Sinister Strike ability by 5.",
                  } },
                { name = "Lightning Reflexes", icon = "spell_nature_invisibilty", row = 1, col = 3, max = 5,
                  ranks = {
                    "Increases your Dodge chance by 1%.",
                    "Increases your Dodge chance by 2%.",
                    "Increases your Dodge chance by 3%.",
                    "Increases your Dodge chance by 4%.",
                    "Increases your Dodge chance by 5%.",
                  } },
                { name = "Improved Slice and Dice", icon = "ability_rogue_slicedice", row = 2, col = 1, max = 3,
                  ranks = {
                    "Increases the duration of your Slice and Dice ability by 15%.",
                    "Increases the duration of your Slice and Dice ability by 30%.",
                    "Increases the duration of your Slice and Dice ability by 45%.",
                  } },
                { name = "Deflection", icon = "ability_parry", row = 2, col = 2, max = 5,
                  ranks = {
                    "Increases your Parry chance by 1%.",
                    "Increases your Parry chance by 2%.",
                    "Increases your Parry chance by 3%.",
                    "Increases your Parry chance by 4%.",
                    "Increases your Parry chance by 5%.",
                  } },
                { name = "Precision", icon = "ability_marksmanship", row = 2, col = 3, max = 5,
                  ranks = {
                    "Increases your chance to hit with weapons by 1%.",
                    "Increases your chance to hit with weapons by 2%.",
                    "Increases your chance to hit with weapons by 3%.",
                    "Increases your chance to hit with weapons by 4%.",
                    "Increases your chance to hit with weapons by 5%.",
                  } },
                { name = "Endurance", icon = "spell_shadow_shadowward", row = 3, col = 1, max = 2,
                  ranks = {
                    "Reduces the cooldown of your Sprint and Evasion abilities by 45 sec.",
                    "Reduces the cooldown of your Sprint and Evasion abilities by 90 sec.",
                  } },
                { name = "Riposte", icon = "ability_warrior_challange", row = 3, col = 2, max = 1, req = "Deflection",
                  ranks = {
                    "A strike that becomes active after parrying an opponent's attack. This attack deals 150% weapon damage and disarms the target for 6 sec.",
                  } },
                { name = "Improved Sprint", icon = "ability_rogue_sprint", row = 3, col = 4, max = 2,
                  ranks = {
                    "Gives a 50% chance to remove all movement impairing effects when you activate your Sprint ability.",
                    "Gives a 100% chance to remove all movement impairing effects when you activate your Sprint ability.",
                  } },
                { name = "Improved Kick", icon = "ability_kick", row = 4, col = 1, max = 2,
                  ranks = {
                    "Gives your Kick ability a 50% chance to silence the target for 2 sec.",
                    "Gives your Kick ability a 100% chance to silence the target for 2 sec.",
                  } },
                { name = "Dagger Specialization", icon = "inv_weapon_shortblade_05", row = 4, col = 2, max = 5,
                  ranks = {
                    "Increases your chance to get a critical strike with Daggers by 1%.",
                    "Increases your chance to get a critical strike with Daggers by 2%.",
                    "Increases your chance to get a critical strike with Daggers by 3%.",
                    "Increases your chance to get a critical strike with Daggers by 4%.",
                    "Increases your chance to get a critical strike with Daggers by 5%.",
                  } },
                { name = "Dual Wield Specialization", icon = "ability_dualwield", row = 4, col = 3, max = 5, req = "Precision",
                  ranks = {
                    "Increases the damage done by your offhand weapon by 10%.",
                    "Increases the damage done by your offhand weapon by 20%.",
                    "Increases the damage done by your offhand weapon by 30%.",
                    "Increases the damage done by your offhand weapon by 40%.",
                    "Increases the damage done by your offhand weapon by 50%.",
                  } },
                { name = "Mace Specialization", icon = "inv_mace_01", row = 5, col = 1, max = 5,
                  ranks = {
                    "Gives you a 1% chance to stun your target for 3 sec with a mace.",
                    "Gives you a 2% chance to stun your target for 3 sec with a mace.",
                    "Gives you a 3% chance to stun your target for 3 sec with a mace.",
                    "Gives you a 4% chance to stun your target for 3 sec with a mace.",
                    "Gives you a 5% chance to stun your target for 3 sec with a mace.",
                  } },
                { name = "Blade Flurry", icon = "ability_warrior_punishingblow", row = 5, col = 2, max = 1,
                  ranks = {
                    "Increases your attack speed by 20%. In addition, attacks strike an additional nearby opponent. Lasts 15 sec.",
                  } },
                { name = "Sword Specialization", icon = "inv_sword_27", row = 5, col = 3, max = 5,
                  ranks = {
                    "Gives you a 1% chance to get an extra attack on the same target after dealing damage with your Sword.",
                    "Gives you a 2% chance to get an extra attack on the same target after dealing damage with your Sword.",
                    "Gives you a 3% chance to get an extra attack on the same target after dealing damage with your Sword.",
                    "Gives you a 4% chance to get an extra attack on the same target after dealing damage with your Sword.",
                    "Gives you a 5% chance to get an extra attack on the same target after dealing damage with your Sword.",
                  } },
                { name = "Fist Weapon Specialization", icon = "inv_gauntlets_04", row = 5, col = 4, max = 5,
                  ranks = {
                    "Increases your chance to get a critical strike with Fist Weapons by 1%.",
                    "Increases your chance to get a critical strike with Fist Weapons by 2%.",
                    "Increases your chance to get a critical strike with Fist Weapons by 3%.",
                    "Increases your chance to get a critical strike with Fist Weapons by 4%.",
                    "Increases your chance to get a critical strike with Fist Weapons by 5%.",
                  } },
                { name = "Blade Twisting", icon = "ability_rogue_bladetwisting", row = 6, col = 1, max = 2,
                  ranks = {
                    "Gives your Sinister Strike, Backstab, Gouge and Shiv abilities a 10% chance to Daze the target for 8 sec.",
                    "Gives your Sinister Strike, Backstab, Gouge and Shiv abilities a 20% chance to Daze the target for 8 sec.",
                  } },
                { name = "Weapon Expertise", icon = "spell_holy_blessingofstrength", row = 6, col = 2, max = 2, req = "Blade Flurry",
                  ranks = {
                    "Increases your expertise by 5.",
                    "Increases your expertise by 10.",
                  } },
                { name = "Aggression", icon = "ability_racial_avatar", row = 6, col = 3, max = 3,
                  ranks = {
                    "Increases the damage of your Sinister Strike, Backstab, and Eviscerate abilities by 2%.",
                    "Increases the damage of your Sinister Strike, Backstab, and Eviscerate abilities by 4%.",
                    "Increases the damage of your Sinister Strike, Backstab, and Eviscerate abilities by 6%.",
                  } },
                { name = "Vitality", icon = "ability_warrior_revenge", row = 7, col = 1, max = 2,
                  ranks = {
                    "Increases your total Stamina by 2% and your total Agility by 1%.",
                    "Increases your total Stamina by 4% and your total Agility by 2%.",
                  } },
                { name = "Adrenaline Rush", icon = "spell_shadow_shadowworddominate", row = 7, col = 2, max = 1,
                  ranks = {
                    "Increases your Energy regeneration rate by 100% for 15 sec.",
                  } },
                { name = "Nerves of Steel", icon = "ability_rogue_nervesofsteel", row = 7, col = 3, max = 2,
                  ranks = {
                    "Increases your chance to resist Stun and Fear effects by an additional 5%.",
                    "Increases your chance to resist Stun and Fear effects by an additional 10%.",
                  } },
                { name = "Combat Potency", icon = "inv_weapon_shortblade_38", row = 8, col = 3, max = 5,
                  ranks = {
                    "Gives your successful off-hand melee attacks a 20% chance to generate 3 Energy.",
                    "Gives your successful off-hand melee attacks a 20% chance to generate 6 Energy.",
                    "Gives your successful off-hand melee attacks a 20% chance to generate 9 Energy.",
                    "Gives your successful off-hand melee attacks a 20% chance to generate 12 Energy.",
                    "Gives your successful off-hand melee attacks a 20% chance to generate 15 Energy.",
                  } },
                { name = "Surprise Attacks", icon = "ability_rogue_surpriseattack", row = 9, col = 2, max = 1, req = "Adrenaline Rush",
                  ranks = {
                    "Your finishing moves can no longer be dodged, and the damage dealt by your Sinister Strike, Backstab, Shiv and Gouge abilities is increased by 10%.",
                  } },
            },
        },
        {
            name = "Subtlety", bg = "RogueSubtlety",
            talents = {
                { name = "Master of Deception", icon = "spell_shadow_charm", row = 1, col = 2, max = 5,
                  ranks = {
                    "Reduces the chance enemies have to detect you while in Stealth mode.",
                    "Reduces the chance enemies have to detect you while in Stealth mode. More effective than Master of Deception (Rank 1).",
                    "Reduces the chance enemies have to detect you while in Stealth mode. More effective than Master of Deception (Rank 2).",
                    "Reduces the chance enemies have to detect you while in Stealth mode. More effective than Master of Deception (Rank 3).",
                    "Reduces the chance enemies have to detect you while in Stealth mode. More effective than Master of Deception (Rank 4).",
                  } },
                { name = "Opportunity", icon = "ability_warrior_warcry", row = 1, col = 3, max = 5,
                  ranks = {
                    "Increases the damage dealt when striking from behind with your Backstab, Mutilate, Garrote and Ambush abilities by 4%.",
                    "Increases the damage dealt when striking from behind with your Backstab, Mutilate, Garrote and Ambush abilities by 8%.",
                    "Increases the damage dealt when striking from behind with your Backstab, Mutilate, Garrote and Ambush abilities by 12%.",
                    "Increases the damage dealt when striking from behind with your Backstab, Mutilate, Garrote and Ambush abilities by 16%.",
                    "Increases the damage dealt when striking from behind with your Backstab, Mutilate, Garrote and Ambush abilities by 20%.",
                  } },
                { name = "Sleight of Hand", icon = "ability_rogue_feint", row = 2, col = 1, max = 2,
                  ranks = {
                    "Reduces the chance you are critically hit by melee and ranged attacks by 1% and increases the threat reduction of your Feint ability by 10%.",
                    "Reduces the chance you are critically hit by melee and ranged attacks by 2% and increases the threat reduction of your Feint ability by 20%.",
                  } },
                { name = "Dirty Tricks", icon = "ability_sap", row = 2, col = 2, max = 2,
                  ranks = {
                    "Increases the range of your Blind and Sap abilities by 2 yards and reduces the energy cost of your Blind and Sap abilities by 25%.",
                    "Increases the range of your Blind and Sap abilities by 5 yards and reduces the energy cost of your Blind and Sap abilities by 50%.",
                  } },
                { name = "Camouflage", icon = "ability_stealth", row = 2, col = 3, max = 5,
                  ranks = {
                    "Increases your speed while stealthed by 3% and reduces the cooldown of your Stealth ability by 1 sec.",
                    "Increases your speed while stealthed by 6% and reduces the cooldown of your Stealth ability by 2 sec.",
                    "Increases your speed while stealthed by 9% and reduces the cooldown of your Stealth ability by 3 sec.",
                    "Increases your speed while stealthed by 12% and reduces the cooldown of your Stealth ability by 4 sec.",
                    "Increases your speed while stealthed by 15% and reduces the cooldown of your Stealth ability by 5 sec.",
                  } },
                { name = "Initiative", icon = "spell_shadow_fumble", row = 3, col = 1, max = 3,
                  ranks = {
                    "Gives you a 25% chance to add an additional combo point to your target when using your Ambush, Garrote, or Cheap Shot ability.",
                    "Gives you a 50% chance to add an additional combo point to your target when using your Ambush, Garrote, or Cheap Shot ability.",
                    "Gives you a 75% chance to add an additional combo point to your target when using your Ambush, Garrote, or Cheap Shot ability.",
                  } },
                { name = "Ghostly Strike", icon = "spell_shadow_curse", row = 3, col = 2, max = 1,
                  ranks = {
                    "A strike that deals 125% weapon damage and increases your chance to dodge by 15% for 7 sec. Awards 1 combo point.",
                  } },
                { name = "Improved Ambush", icon = "ability_rogue_ambush", row = 3, col = 3, max = 3,
                  ranks = {
                    "Increases the critical strike chance of your Ambush ability by 15%.",
                    "Increases the critical strike chance of your Ambush ability by 30%.",
                    "Increases the critical strike chance of your Ambush ability by 45%.",
                  } },
                { name = "Setup", icon = "spell_nature_mirrorimage", row = 4, col = 1, max = 3,
                  ranks = {
                    "Gives you a 15% chance to add a combo point to your target after dodging their attack or fully resisting one of their spells.",
                    "Gives you a 30% chance to add a combo point to your target after dodging their attack or fully resisting one of their spells.",
                    "Gives you a 45% chance to add a combo point to your target after dodging their attack or fully resisting one of their spells.",
                  } },
                { name = "Elusiveness", icon = "spell_magic_lesserinvisibilty", row = 4, col = 2, max = 2,
                  ranks = {
                    "Reduces the cooldown of your Vanish and Blind abilities by 45 sec.",
                    "Reduces the cooldown of your Vanish and Blind abilities by 90 sec.",
                  } },
                { name = "Serrated Blades", icon = "inv_sword_17", row = 4, col = 3, max = 3,
                  ranks = {
                    "Causes your attacks to ignore 194 of your target's armor and increases the damage dealt by your Rupture ability by 10%. The amount of armor reduced increases with your level.",
                    "Causes your attacks to ignore 388 of your target's armor and increases the damage dealt by your Rupture ability by 20%. The amount of armor reduced increases with your level.",
                    "Causes your attacks to ignore 582 of your target's armor and increases the damage dealt by your Rupture ability by 30%. The amount of armor reduced increases with your level.",
                  } },
                { name = "Heightened Senses", icon = "ability_ambush", row = 5, col = 1, max = 2,
                  ranks = {
                    "Increases your Stealth detection and reduces the chance you are hit by spells and ranged attacks by 2%.",
                    "Increases your Stealth detection and reduces the chance you are hit by spells and ranged attacks by 4%.",
                  } },
                { name = "Preparation", icon = "spell_shadow_antishadow", row = 5, col = 2, max = 1,
                  ranks = {
                    "When activated, this ability immediately finishes the cooldown on your Evasion, Sprint, Vanish, Cold Blood, Shadowstep and Premeditation abilities.",
                  } },
                { name = "Dirty Deeds", icon = "spell_shadow_summonsuccubus", row = 5, col = 3, max = 2,
                  ranks = {
                    "Reduces the Energy cost of your Cheap Shot and Garrote abilities by 10. Additionally, your special abilities cause 10% more damage against targets below 35% health.",
                    "Reduces the Energy cost of your Cheap Shot and Garrote abilities by 20. Additionally, your special abilities cause 20% more damage against targets below 35% health.",
                  } },
                { name = "Hemorrhage", icon = "spell_shadow_lifedrain", row = 5, col = 4, max = 1, req = "Serrated Blades",
                  ranks = {
                    "An instant strike that deals 110% weapon damage and causes the target to hemorrhage, increasing any Physical damage dealt to the target by up to 13. Lasts 10 charges or 15 sec. Awards 1 combo point.",
                  } },
                { name = "Master of Subtlety", icon = "ability_rogue_masterofsubtlety", row = 6, col = 1, max = 3,
                  ranks = {
                    "Attacks made while stealthed and for 6 seconds after breaking stealth cause an additional 4% damage.",
                    "Attacks made while stealthed and for 6 seconds after breaking stealth cause an additional 7% damage.",
                    "Attacks made while stealthed and for 6 seconds after breaking stealth cause an additional 10% damage.",
                  } },
                { name = "Deadliness", icon = "inv_weapon_crossbow_11", row = 6, col = 3, max = 5,
                  ranks = {
                    "Increases your attack power by 2%.",
                    "Increases your attack power by 4%.",
                    "Increases your attack power by 6%.",
                    "Increases your attack power by 8%.",
                    "Increases your attack power by 10%.",
                  } },
                { name = "Enveloping Shadows", icon = "ability_rogue_envelopingshadows", row = 7, col = 1, max = 3,
                  ranks = {
                    "Increases your chance to avoid area of effect attacks by an additional 5%.",
                    "Increases your chance to avoid area of effect attacks by an additional 10%.",
                    "Increases your chance to avoid area of effect attacks by an additional 15%.",
                  } },
                { name = "Premeditation", icon = "spell_shadow_possession", row = 7, col = 2, max = 1, req = "Preparation",
                  ranks = {
                    "When used, adds 2 combo points to your target. You must add to or use those combo points within 10 sec or the combo points are lost.",
                  } },
                { name = "Cheat Death", icon = "ability_rogue_cheatdeath", row = 7, col = 3, max = 3,
                  ranks = {
                    "You have a 33% chance that an attack which would otherwise kill you will instead reduce you to 10% of your maximum health. In addition, all damage taken will be reduced by up to 90% for 3 sec (modified by resilience). This effect cannot occur more than once per minute.",
                    "You have a 66% chance that an attack which would otherwise kill you will instead reduce you to 10% of your maximum health. In addition, all damage taken will be reduced by up to 90% for 3 sec (modified by resilience). This effect cannot occur more than once per minute.",
                    "You have a 100% chance that an attack which would otherwise kill you will instead reduce you to 10% of your maximum health. In addition, all damage taken will be reduced by up to 90% for 3 sec (modified by resilience). This effect cannot occur more than once per minute.",
                  } },
                { name = "Sinister Calling", icon = "ability_rogue_sinistercalling", row = 8, col = 2, max = 5, req = "Premeditation",
                  ranks = {
                    "Increases your total Agility by 3% and increases the percentage damage bonus of Backstab and Hemorrhage by an additional 1%.",
                    "Increases your total Agility by 6% and increases the percentage damage bonus of Backstab and Hemorrhage by an additional 2%.",
                    "Increases your total Agility by 9% and increases the percentage damage bonus of Backstab and Hemorrhage by an additional 3%.",
                    "Increases your total Agility by 12% and increases the percentage damage bonus of Backstab and Hemorrhage by an additional 4%.",
                    "Increases your total Agility by 15% and increases the percentage damage bonus of Backstab and Hemorrhage by an additional 5%.",
                  } },
                { name = "Shadowstep", icon = "ability_rogue_shadowstep", row = 9, col = 2, max = 1,
                  ranks = {
                    "Attempts to step through the shadows and reappear behind your enemy and increases movement speed by 70% for 3 sec. The damage of your next ability is increased by 20% and the threat caused is reduced by 50%. Lasts 10 sec.",
                  } },
            },
        },
    },
    builds = {
        { key = "ASSASSINATION", name = "Assassination", role = "MELEE",
          points = {
            [1] = {
                ["Malice"] = 5,
                ["Ruthlessness"] = 3,
                ["Murder"] = 2,
                ["Puncturing Wounds"] = 3,
                ["Relentless Strikes"] = 1,
                ["Lethality"] = 5,
                ["Vile Poisons"] = 5,
                ["Improved Poisons"] = 4,
                ["Cold Blood"] = 1,
                ["Seal Fate"] = 5,
                ["Vigor"] = 1,
                ["Find Weakness"] = 5,
                ["Mutilate"] = 1,
            },
            [2] = {
                ["Lightning Reflexes"] = 5,
                ["Improved Slice and Dice"] = 3,
                ["Precision"] = 5,
                ["Endurance"] = 2,
                ["Dual Wield Specialization"] = 5,
            },
          },
          stats = {
            "Hit rating to the 9% special cap (142; Precision covers 5%)",
            "Expertise to 26 (dodge capped from behind)",
            "Poison hit via spell hit (16% cap; rarely chased on gear)",
            "Agility",
            "Attack power",
            "Crit rating",
            "Haste rating",
          },
          notes = "The 41/20/0 Mutilate raid build: stay behind the boss, keep Slice and Dice rolling, and spend 4-5 point Envenoms or Ruptures with Cold Blood glued to a finisher. The fifth Improved Poisons point can move to Master Poisoner or Quick Recovery, and Dagger Specialization can replace Dual Wield Specialization if you prefer crit over offhand damage." },
        { key = "COMBAT", name = "Combat", role = "MELEE",
          points = {
            [1] = {
                ["Improved Eviscerate"] = 3,
                ["Remorseless Attacks"] = 1,
                ["Malice"] = 5,
                ["Ruthlessness"] = 3,
                ["Murder"] = 2,
                ["Relentless Strikes"] = 1,
                ["Lethality"] = 5,
            },
            [2] = {
                ["Improved Sinister Strike"] = 2,
                ["Lightning Reflexes"] = 3,
                ["Improved Slice and Dice"] = 3,
                ["Precision"] = 5,
                ["Endurance"] = 2,
                ["Dual Wield Specialization"] = 5,
                ["Sword Specialization"] = 5,
                ["Blade Flurry"] = 1,
                ["Weapon Expertise"] = 2,
                ["Aggression"] = 3,
                ["Vitality"] = 2,
                ["Adrenaline Rush"] = 1,
                ["Nerves of Steel"] = 1,
                ["Combat Potency"] = 5,
                ["Surprise Attacks"] = 1,
            },
          },
          stats = {
            "Hit rating to the 9% special cap (142; Precision covers 5%)",
            "Expertise to 26 (Weapon Expertise supplies 10)",
            "Agility",
            "Attack power",
            "Crit rating",
            "Haste rating",
            "Armor penetration",
          },
          notes = "The classic 20/41/0 combat swords raid spec: Sinister Strike into a permanent Slice and Dice, Rupture when it fits, and Blade Flurry chained with Adrenaline Rush on cooldown. Lightning Reflexes, Endurance, and the lone Nerves of Steel point are pure fillers - shift them into Improved Kick or Improved Sprint on demand, and fist or mace mains swap Sword Specialization for their own weapon talent." },
    },
}
