-- Commander_Talents — SHAMAN talent data (GENERATED 2026-08-04).
-- TBC 2.4.3 final talent state. Regenerate via an agent pass against
-- prompts/commander-talents.md; after any hand-edit, re-run
-- Harness/validate_class_data.lua.

CommanderTalentsData.Classes.SHAMAN = {
    trees = {
        {
            name = "Elemental", bg = "ShamanElementalCombat",
            talents = {
                { name = "Convection", icon = "spell_nature_wispsplode", row = 1, col = 2, max = 5,
                  ranks = {
                      "Reduces the mana cost of your Shock, Lightning Bolt and Chain Lightning spells by 2%.",
                      "Reduces the mana cost of your Shock, Lightning Bolt and Chain Lightning spells by 4%.",
                      "Reduces the mana cost of your Shock, Lightning Bolt and Chain Lightning spells by 6%.",
                      "Reduces the mana cost of your Shock, Lightning Bolt and Chain Lightning spells by 8%.",
                      "Reduces the mana cost of your Shock, Lightning Bolt and Chain Lightning spells by 10%.",
                  } },
                { name = "Concussion", icon = "spell_fire_fireball", row = 1, col = 3, max = 5,
                  ranks = {
                      "Increases the damage done by your Lightning Bolt, Chain Lightning and Shock spells by 1%.",
                      "Increases the damage done by your Lightning Bolt, Chain Lightning and Shock spells by 2%.",
                      "Increases the damage done by your Lightning Bolt, Chain Lightning and Shock spells by 3%.",
                      "Increases the damage done by your Lightning Bolt, Chain Lightning and Shock spells by 4%.",
                      "Increases the damage done by your Lightning Bolt, Chain Lightning and Shock spells by 5%.",
                  } },
                { name = "Earth's Grasp", icon = "spell_nature_stoneclawtotem", row = 2, col = 1, max = 2,
                  ranks = {
                      "Increases the health of your Stoneclaw Totem by 25% and the radius of your Earthbind Totem by 10%.",
                      "Increases the health of your Stoneclaw Totem by 50% and the radius of your Earthbind Totem by 20%.",
                  } },
                { name = "Elemental Warding", icon = "spell_nature_spiritarmor", row = 2, col = 2, max = 3,
                  ranks = {
                      "Reduces damage taken from Fire, Frost and Nature effects by 4%.",
                      "Reduces damage taken from Fire, Frost and Nature effects by 7%.",
                      "Reduces damage taken from Fire, Frost and Nature effects by 10%.",
                  } },
                { name = "Call of Flame", icon = "spell_fire_immolation", row = 2, col = 3, max = 3,
                  ranks = {
                      "Increases the damage done by your Fire Totems by 5%.",
                      "Increases the damage done by your Fire Totems by 10%.",
                      "Increases the damage done by your Fire Totems by 15%.",
                  } },
                { name = "Elemental Focus", icon = "spell_shadow_manaburn", row = 3, col = 1, max = 1,
                  ranks = {
                      "After landing a critical strike with a Fire, Frost, or Nature damage spell, you enter a Clearcasting state. The Clearcasting state reduces the mana cost of your next 2 damage spells by 40%.",
                  } },
                { name = "Reverberation", icon = "spell_frost_frostward", row = 3, col = 2, max = 5,
                  ranks = {
                      "Reduces the cooldown of your Shock spells by 0.2 sec.",
                      "Reduces the cooldown of your Shock spells by 0.4 sec.",
                      "Reduces the cooldown of your Shock spells by 0.6 sec.",
                      "Reduces the cooldown of your Shock spells by 0.8 sec.",
                      "Reduces the cooldown of your Shock spells by 1 sec.",
                  } },
                { name = "Call of Thunder", icon = "spell_nature_callstorm", row = 3, col = 3, max = 5,
                  ranks = {
                      "Increases the critical strike chance of your Lightning Bolt and Chain Lightning spells by an additional 1%.",
                      "Increases the critical strike chance of your Lightning Bolt and Chain Lightning spells by an additional 2%.",
                      "Increases the critical strike chance of your Lightning Bolt and Chain Lightning spells by an additional 3%.",
                      "Increases the critical strike chance of your Lightning Bolt and Chain Lightning spells by an additional 4%.",
                      "Increases the critical strike chance of your Lightning Bolt and Chain Lightning spells by an additional 6%.",
                  } },
                { name = "Improved Fire Totems", icon = "spell_fire_sealoffire", row = 4, col = 1, max = 2,
                  ranks = {
                      "Reduces the delay before your Fire Nova Totem activates by 1 sec.",
                      "Reduces the delay before your Fire Nova Totem activates by 2 sec.",
                  } },
                { name = "Eye of the Storm", icon = "spell_shadow_soulleech_2", row = 4, col = 2, max = 3,
                  ranks = {
                      "Gives you a 33% chance to avoid interruption caused by damage while casting Lightning Bolt, Chain Lightning and Shock spells.",
                      "Gives you a 66% chance to avoid interruption caused by damage while casting Lightning Bolt, Chain Lightning and Shock spells.",
                      "Gives you a 100% chance to avoid interruption caused by damage while casting Lightning Bolt, Chain Lightning and Shock spells.",
                  } },
                { name = "Elemental Devastation", icon = "spell_fire_elementaldevastation", row = 4, col = 4, max = 3,
                  ranks = {
                      "Your offensive spell crits will increase your chance to get a critical strike with melee attacks by 3% for 10 sec.",
                      "Your offensive spell crits will increase your chance to get a critical strike with melee attacks by 6% for 10 sec.",
                      "Your offensive spell crits will increase your chance to get a critical strike with melee attacks by 9% for 10 sec.",
                  } },
                { name = "Storm Reach", icon = "spell_nature_stormreach", row = 5, col = 1, max = 2,
                  ranks = {
                      "Increases the range of your Lightning Bolt and Chain Lightning spells by 3 yards.",
                      "Increases the range of your Lightning Bolt and Chain Lightning spells by 6 yards.",
                  } },
                { name = "Elemental Fury", icon = "spell_fire_volcano", row = 5, col = 2, max = 1,
                  ranks = {
                      "Increases the critical strike damage bonus of your Searing, Magma, and Fire Nova Totems and your Fire, Frost, and Nature spells by 100%.",
                  } },
                { name = "Unrelenting Storm", icon = "spell_nature_unrelentingstorm", row = 5, col = 4, max = 5,
                  ranks = {
                      "Regenerate mana equal to 2% of your Intellect every 5 sec, even while casting.",
                      "Regenerate mana equal to 4% of your Intellect every 5 sec, even while casting.",
                      "Regenerate mana equal to 6% of your Intellect every 5 sec, even while casting.",
                      "Regenerate mana equal to 8% of your Intellect every 5 sec, even while casting.",
                      "Regenerate mana equal to 10% of your Intellect every 5 sec, even while casting.",
                  } },
                { name = "Elemental Precision", icon = "spell_nature_elementalprecision_1", row = 6, col = 1, max = 3,
                  ranks = {
                      "Increases your chance to hit with Fire, Frost and Nature spells by 2% and reduces the threat caused by Fire, Frost and Nature spells by 4%.",
                      "Increases your chance to hit with Fire, Frost and Nature spells by 4% and reduces the threat caused by Fire, Frost and Nature spells by 7%.",
                      "Increases your chance to hit with Fire, Frost and Nature spells by 6% and reduces the threat caused by Fire, Frost and Nature spells by 10%.",
                  } },
                { name = "Lightning Mastery", icon = "spell_lightning_lightningbolt01", row = 6, col = 3, max = 5,
                  ranks = {
                      "Reduces the cast time of your Lightning Bolt and Chain Lightning spells by 0.1 sec.",
                      "Reduces the cast time of your Lightning Bolt and Chain Lightning spells by 0.2 sec.",
                      "Reduces the cast time of your Lightning Bolt and Chain Lightning spells by 0.3 sec.",
                      "Reduces the cast time of your Lightning Bolt and Chain Lightning spells by 0.4 sec.",
                      "Reduces the cast time of your Lightning Bolt and Chain Lightning spells by 0.5 sec.",
                  } },
                { name = "Elemental Mastery", icon = "spell_nature_wispheal", row = 7, col = 2, max = 1, req = "Elemental Fury",
                  ranks = {
                      "When activated, this spell gives your next Fire, Frost, or Nature damage spell a 100% critical strike chance and reduces the mana cost by 100%.",
                  } },
                { name = "Elemental Shields", icon = "spell_nature_skinofearth", row = 7, col = 3, max = 3,
                  ranks = {
                      "Reduces the chance you will be critically hit by melee and ranged attacks by 2%.",
                      "Reduces the chance you will be critically hit by melee and ranged attacks by 4%.",
                      "Reduces the chance you will be critically hit by melee and ranged attacks by 6%.",
                  } },
                { name = "Lightning Overload", icon = "spell_nature_lightningoverload", row = 8, col = 2, max = 5,
                  ranks = {
                      "Gives your Lightning Bolt and Chain Lightning spells a 4% chance to cast a second, similar spell on the same target at no additional cost that causes half damage and no threat.",
                      "Gives your Lightning Bolt and Chain Lightning spells an 8% chance to cast a second, similar spell on the same target at no additional cost that causes half damage and no threat.",
                      "Gives your Lightning Bolt and Chain Lightning spells a 12% chance to cast a second, similar spell on the same target at no additional cost that causes half damage and no threat.",
                      "Gives your Lightning Bolt and Chain Lightning spells a 16% chance to cast a second, similar spell on the same target at no additional cost that causes half damage and no threat.",
                      "Gives your Lightning Bolt and Chain Lightning spells a 20% chance to cast a second, similar spell on the same target at no additional cost that causes half damage and no threat.",
                  } },
                { name = "Totem of Wrath", icon = "spell_fire_totemofwrath", row = 9, col = 2, max = 1,
                  ranks = {
                      "Summons a Totem of Wrath with 5 health at the feet of the caster. The totem increases the chance to hit and critically strike with spells by 3% for all party members within 20 yards. Lasts 2 min.",
                  } },
            },
        },
        {
            name = "Enhancement", bg = "ShamanEnhancement",
            talents = {
                { name = "Ancestral Knowledge", icon = "spell_shadow_grimward", row = 1, col = 2, max = 5,
                  ranks = {
                      "Increases your maximum Mana by 1%.",
                      "Increases your maximum Mana by 2%.",
                      "Increases your maximum Mana by 3%.",
                      "Increases your maximum Mana by 4%.",
                      "Increases your maximum Mana by 5%.",
                  } },
                { name = "Shield Specialization", icon = "inv_shield_06", row = 1, col = 3, max = 5,
                  ranks = {
                      "Increases your chance to block attacks with a shield by 1% and increases the amount blocked by 5%.",
                      "Increases your chance to block attacks with a shield by 2% and increases the amount blocked by 10%.",
                      "Increases your chance to block attacks with a shield by 3% and increases the amount blocked by 15%.",
                      "Increases your chance to block attacks with a shield by 4% and increases the amount blocked by 20%.",
                      "Increases your chance to block attacks with a shield by 5% and increases the amount blocked by 25%.",
                  } },
                { name = "Guardian Totems", icon = "spell_nature_stoneskintotem", row = 2, col = 1, max = 2,
                  ranks = {
                      "Increases the amount of damage reduced by your Stoneskin Totem by 10% and reduces the cooldown of your Grounding Totem by 2 sec.",
                      "Increases the amount of damage reduced by your Stoneskin Totem by 20% and reduces the cooldown of your Grounding Totem by 4 sec.",
                  } },
                { name = "Thundering Strikes", icon = "ability_thunderbolt", row = 2, col = 2, max = 5,
                  ranks = {
                      "Improves your chance to get a critical strike with your weapon attacks by 1%.",
                      "Improves your chance to get a critical strike with your weapon attacks by 2%.",
                      "Improves your chance to get a critical strike with your weapon attacks by 3%.",
                      "Improves your chance to get a critical strike with your weapon attacks by 4%.",
                      "Improves your chance to get a critical strike with your weapon attacks by 5%.",
                  } },
                { name = "Improved Ghost Wolf", icon = "spell_nature_spiritwolf", row = 2, col = 3, max = 2,
                  ranks = {
                      "Reduces the cast time of your Ghost Wolf spell by 1 sec.",
                      "Reduces the cast time of your Ghost Wolf spell by 2 sec.",
                  } },
                { name = "Improved Lightning Shield", icon = "spell_nature_lightningshield", row = 2, col = 4, max = 3,
                  ranks = {
                      "Increases the damage done by your Lightning Shield orbs by 5%.",
                      "Increases the damage done by your Lightning Shield orbs by 10%.",
                      "Increases the damage done by your Lightning Shield orbs by 15%.",
                  } },
                { name = "Enhancing Totems", icon = "spell_nature_earthbindtotem", row = 3, col = 1, max = 2,
                  ranks = {
                      "Increases the effect of your Strength of Earth and Grace of Air Totems by 8%.",
                      "Increases the effect of your Strength of Earth and Grace of Air Totems by 15%.",
                  } },
                { name = "Shamanistic Focus", icon = "spell_nature_elementalabsorption", row = 3, col = 3, max = 1,
                  ranks = {
                      "After landing a melee critical strike, you enter a Focused state. The Focused state reduces the mana cost of your next Shock spell by 60%.",
                  } },
                { name = "Anticipation", icon = "spell_nature_mirrorimage", row = 3, col = 4, max = 3,
                  ranks = {
                      "Increases your chance to dodge by an additional 1%.",
                      "Increases your chance to dodge by an additional 2%.",
                      "Increases your chance to dodge by an additional 3%.",
                  } },
                { name = "Flurry", icon = "ability_ghoulfrenzy", row = 4, col = 2, max = 5, req = "Thundering Strikes",
                  ranks = {
                      "Increases your attack speed by 10% for your next 3 swings after dealing a critical strike.",
                      "Increases your attack speed by 15% for your next 3 swings after dealing a critical strike.",
                      "Increases your attack speed by 20% for your next 3 swings after dealing a critical strike.",
                      "Increases your attack speed by 25% for your next 3 swings after dealing a critical strike.",
                      "Increases your attack speed by 30% for your next 3 swings after dealing a critical strike.",
                  } },
                { name = "Toughness", icon = "spell_holy_devotion", row = 4, col = 3, max = 5,
                  ranks = {
                      "Increases your armor value from items by 2%.",
                      "Increases your armor value from items by 4%.",
                      "Increases your armor value from items by 6%.",
                      "Increases your armor value from items by 8%.",
                      "Increases your armor value from items by 10%.",
                  } },
                { name = "Improved Weapon Totems", icon = "spell_fire_enchantweapon", row = 5, col = 1, max = 2,
                  ranks = {
                      "Increases the melee attack power bonus of your Windfury Totem by 15% and increases the damage caused by your Flametongue Totem by 6%.",
                      "Increases the melee attack power bonus of your Windfury Totem by 30% and increases the damage caused by your Flametongue Totem by 12%.",
                  } },
                { name = "Spirit Weapons", icon = "ability_parry", row = 5, col = 2, max = 1,
                  ranks = {
                      "Gives a chance to parry enemy melee attacks and reduces the threat generated by your melee attacks by 30%.",
                  } },
                { name = "Elemental Weapons", icon = "spell_fire_flametounge", row = 5, col = 3, max = 3,
                  ranks = {
                      "Increases the melee attack power bonus of your Rockbiter Weapon by 7%, your Windfury Weapon effect by 13% and increases the damage caused by your Flametongue Weapon and Frostbrand Weapon by 5%.",
                      "Increases the melee attack power bonus of your Rockbiter Weapon by 14%, your Windfury Weapon effect by 27% and increases the damage caused by your Flametongue Weapon and Frostbrand Weapon by 10%.",
                      "Increases the melee attack power bonus of your Rockbiter Weapon by 20%, your Windfury Weapon effect by 40% and increases the damage caused by your Flametongue Weapon and Frostbrand Weapon by 15%.",
                  } },
                { name = "Mental Quickness", icon = "spell_nature_mentalquickness", row = 6, col = 1, max = 3,
                  ranks = {
                      "Reduces the mana cost of your instant cast Shaman spells by 2% and increases your spell damage and healing equal to 10% of your attack power.",
                      "Reduces the mana cost of your instant cast Shaman spells by 4% and increases your spell damage and healing equal to 20% of your attack power.",
                      "Reduces the mana cost of your instant cast Shaman spells by 6% and increases your spell damage and healing equal to 30% of your attack power.",
                  } },
                { name = "Weapon Mastery", icon = "ability_hunter_swiftstrike", row = 6, col = 4, max = 5,
                  ranks = {
                      "Increases the damage you deal with all weapons by 2%.",
                      "Increases the damage you deal with all weapons by 4%.",
                      "Increases the damage you deal with all weapons by 6%.",
                      "Increases the damage you deal with all weapons by 8%.",
                      "Increases the damage you deal with all weapons by 10%.",
                  } },
                { name = "Dual Wield Specialization", icon = "ability_dualwieldspecialization", row = 7, col = 1, max = 3, req = "Dual Wield",
                  ranks = {
                      "Increases your chance to hit while dual wielding by an additional 2%.",
                      "Increases your chance to hit while dual wielding by an additional 4%.",
                      "Increases your chance to hit while dual wielding by an additional 6%.",
                  } },
                { name = "Dual Wield", icon = "ability_dualwield", row = 7, col = 2, max = 1,
                  ranks = {
                      "Allows one-hand and off-hand weapons to be equipped in the off-hand.",
                  } },
                { name = "Stormstrike", icon = "spell_holy_sealofmight", row = 7, col = 3, max = 1,
                  ranks = {
                      "Instantly attack with both weapons. In addition, the next 2 sources of Nature damage dealt to the target from the Shaman are increased by 20%. Lasts 12 sec.",
                  } },
                { name = "Unleashed Rage", icon = "spell_nature_unleashedrage", row = 8, col = 2, max = 5,
                  ranks = {
                      "Causes your critical hits with melee attacks to increase all party members' melee attack power by 2% if within 20 yards of the Shaman. Lasts 10 sec.",
                      "Causes your critical hits with melee attacks to increase all party members' melee attack power by 4% if within 20 yards of the Shaman. Lasts 10 sec.",
                      "Causes your critical hits with melee attacks to increase all party members' melee attack power by 6% if within 20 yards of the Shaman. Lasts 10 sec.",
                      "Causes your critical hits with melee attacks to increase all party members' melee attack power by 8% if within 20 yards of the Shaman. Lasts 10 sec.",
                      "Causes your critical hits with melee attacks to increase all party members' melee attack power by 10% if within 20 yards of the Shaman. Lasts 10 sec.",
                  } },
                { name = "Shamanistic Rage", icon = "spell_nature_shamanrage", row = 9, col = 2, max = 1,
                  ranks = {
                      "Reduces all damage taken by 30% and gives your successful melee attacks a chance to regenerate mana equal to 30% of your attack power. Lasts 15 sec.",
                  } },
            },
        },
        {
            name = "Restoration", bg = "ShamanRestoration",
            talents = {
                { name = "Improved Healing Wave", icon = "spell_nature_magicimmunity", row = 1, col = 2, max = 5,
                  ranks = {
                      "Reduces the casting time of your Healing Wave spell by 0.1 sec.",
                      "Reduces the casting time of your Healing Wave spell by 0.2 sec.",
                      "Reduces the casting time of your Healing Wave spell by 0.3 sec.",
                      "Reduces the casting time of your Healing Wave spell by 0.4 sec.",
                      "Reduces the casting time of your Healing Wave spell by 0.5 sec.",
                  } },
                { name = "Tidal Focus", icon = "spell_frost_manarecharge", row = 1, col = 3, max = 5,
                  ranks = {
                      "Reduces the mana cost of your healing spells by 1%.",
                      "Reduces the mana cost of your healing spells by 2%.",
                      "Reduces the mana cost of your healing spells by 3%.",
                      "Reduces the mana cost of your healing spells by 4%.",
                      "Reduces the mana cost of your healing spells by 5%.",
                  } },
                { name = "Improved Reincarnation", icon = "spell_nature_reincarnation", row = 2, col = 1, max = 2,
                  ranks = {
                      "Reduces the cooldown of your Reincarnation spell by 10 minutes and increases the amount of health and mana you reincarnate with by an additional 5%.",
                      "Reduces the cooldown of your Reincarnation spell by 20 minutes and increases the amount of health and mana you reincarnate with by an additional 10%.",
                  } },
                { name = "Ancestral Healing", icon = "spell_nature_undyingstrength", row = 2, col = 2, max = 3,
                  ranks = {
                      "Increases your target's armor value from items by 8% for 15 sec after getting a critical effect from one of your healing spells.",
                      "Increases your target's armor value from items by 16% for 15 sec after getting a critical effect from one of your healing spells.",
                      "Increases your target's armor value from items by 25% for 15 sec after getting a critical effect from one of your healing spells.",
                  } },
                { name = "Totemic Focus", icon = "spell_nature_moonglow", row = 2, col = 3, max = 5,
                  ranks = {
                      "Reduces the Mana cost of your totems by 5%.",
                      "Reduces the Mana cost of your totems by 10%.",
                      "Reduces the Mana cost of your totems by 15%.",
                      "Reduces the Mana cost of your totems by 20%.",
                      "Reduces the Mana cost of your totems by 25%.",
                  } },
                { name = "Nature's Guidance", icon = "spell_frost_stun", row = 3, col = 1, max = 3,
                  ranks = {
                      "Increases your chance to hit with melee attacks and spells by 1%.",
                      "Increases your chance to hit with melee attacks and spells by 2%.",
                      "Increases your chance to hit with melee attacks and spells by 3%.",
                  } },
                { name = "Healing Focus", icon = "spell_nature_healingwavelesser", row = 3, col = 2, max = 5,
                  ranks = {
                      "Gives you a 14% chance to avoid interruption caused by damage while casting any healing spell.",
                      "Gives you a 28% chance to avoid interruption caused by damage while casting any healing spell.",
                      "Gives you a 42% chance to avoid interruption caused by damage while casting any healing spell.",
                      "Gives you a 56% chance to avoid interruption caused by damage while casting any healing spell.",
                      "Gives you a 70% chance to avoid interruption caused by damage while casting any healing spell.",
                  } },
                { name = "Totemic Mastery", icon = "spell_nature_nullward", row = 3, col = 3, max = 1,
                  ranks = {
                      "The radius of your totems that affect friendly targets is increased to 30 yd.",
                  } },
                { name = "Healing Grace", icon = "spell_nature_healingtouch", row = 3, col = 4, max = 3,
                  ranks = {
                      "Reduces the threat generated by your healing spells by 5% and reduces the chance your spells will be dispelled by 10%.",
                      "Reduces the threat generated by your healing spells by 10% and reduces the chance your spells will be dispelled by 20%.",
                      "Reduces the threat generated by your healing spells by 15% and reduces the chance your spells will be dispelled by 30%.",
                  } },
                { name = "Restorative Totems", icon = "spell_nature_manaregentotem", row = 4, col = 2, max = 5,
                  ranks = {
                      "Increases the effect of your Mana Spring and Healing Stream Totems by 5%.",
                      "Increases the effect of your Mana Spring and Healing Stream Totems by 10%.",
                      "Increases the effect of your Mana Spring and Healing Stream Totems by 15%.",
                      "Increases the effect of your Mana Spring and Healing Stream Totems by 20%.",
                      "Increases the effect of your Mana Spring and Healing Stream Totems by 25%.",
                  } },
                { name = "Tidal Mastery", icon = "spell_nature_tranquility", row = 4, col = 3, max = 5,
                  ranks = {
                      "Increases the critical effect chance of your healing and lightning spells by 1%.",
                      "Increases the critical effect chance of your healing and lightning spells by 2%.",
                      "Increases the critical effect chance of your healing and lightning spells by 3%.",
                      "Increases the critical effect chance of your healing and lightning spells by 4%.",
                      "Increases the critical effect chance of your healing and lightning spells by 5%.",
                  } },
                { name = "Healing Way", icon = "spell_nature_healingway", row = 5, col = 1, max = 3,
                  ranks = {
                      "Your Healing Wave spells have a 33% chance to increase the effect of subsequent Healing Wave spells on that target by 6% for 15 sec. This effect will stack up to 3 times.",
                      "Your Healing Wave spells have a 66% chance to increase the effect of subsequent Healing Wave spells on that target by 6% for 15 sec. This effect will stack up to 3 times.",
                      "Your Healing Wave spells have a 100% chance to increase the effect of subsequent Healing Wave spells on that target by 6% for 15 sec. This effect will stack up to 3 times.",
                  } },
                { name = "Nature's Swiftness", icon = "spell_nature_ravenform", row = 5, col = 3, max = 1,
                  ranks = {
                      "When activated, your next Nature spell with a casting time less than 10 sec. becomes an instant cast spell.",
                  } },
                { name = "Focused Mind", icon = "spell_nature_focusedmind", row = 5, col = 4, max = 3,
                  ranks = {
                      "Increases your chance to resist Silence and Interrupt mechanics by an additional 5%.",
                      "Increases your chance to resist Silence and Interrupt mechanics by an additional 10%.",
                      "Increases your chance to resist Silence and Interrupt mechanics by an additional 15%.",
                  } },
                { name = "Nature's Guardian", icon = "spell_nature_natureguardian", row = 6, col = 1, max = 5,
                  ranks = {
                      "While below 30% health, you have a 10% chance when hit by a melee or ranged attack to heal for 10% of your total health and reduce your threat level toward the attacker. 5 second cooldown.",
                      "While below 30% health, you have a 20% chance when hit by a melee or ranged attack to heal for 10% of your total health and reduce your threat level toward the attacker. 5 second cooldown.",
                      "While below 30% health, you have a 30% chance when hit by a melee or ranged attack to heal for 10% of your total health and reduce your threat level toward the attacker. 5 second cooldown.",
                      "While below 30% health, you have a 40% chance when hit by a melee or ranged attack to heal for 10% of your total health and reduce your threat level toward the attacker. 5 second cooldown.",
                      "While below 30% health, you have a 50% chance when hit by a melee or ranged attack to heal for 10% of your total health and reduce your threat level toward the attacker. 5 second cooldown.",
                  } },
                { name = "Purification", icon = "spell_frost_wizardmark", row = 6, col = 3, max = 5,
                  ranks = {
                      "Increases the effectiveness of your healing spells by 2%.",
                      "Increases the effectiveness of your healing spells by 4%.",
                      "Increases the effectiveness of your healing spells by 6%.",
                      "Increases the effectiveness of your healing spells by 8%.",
                      "Increases the effectiveness of your healing spells by 10%.",
                  } },
                { name = "Mana Tide Totem", icon = "spell_frost_summonwaterelemental", row = 7, col = 2, max = 1, req = "Restorative Totems",
                  ranks = {
                      "Summons a Mana Tide Totem with 5 health at the feet of the caster for 12 sec that restores 6% of total mana every 3 seconds to group members within 20 yards.",
                  } },
                { name = "Improved Chain Heal", icon = "spell_nature_healingwavegreater", row = 7, col = 3, max = 2,
                  ranks = {
                      "Increases the amount healed by your Chain Heal spell by 10%.",
                      "Increases the amount healed by your Chain Heal spell by 20%.",
                  } },
                { name = "Nature's Blessing", icon = "spell_nature_natureblessing", row = 8, col = 2, max = 3,
                  ranks = {
                      "Increases your spell damage and healing by an amount equal to 10% of your Intellect.",
                      "Increases your spell damage and healing by an amount equal to 20% of your Intellect.",
                      "Increases your spell damage and healing by an amount equal to 30% of your Intellect.",
                  } },
                { name = "Earth Shield", icon = "spell_nature_skinofearth", row = 9, col = 2, max = 1,
                  ranks = {
                      "Protects the target with an earthen shield, reducing casting or channeling time lost when damaged by 30% and causing attacks to heal the shielded target for 150. This effect can only occur once every few seconds. 10 charges. Lasts 10 min. Earth Shield can only be placed on one target at a time and only one Elemental Shield can be active on a target at a time.",
                  } },
            },
        },
    },
    builds = {
        { key = "ELEMENTAL", name = "Elemental", role = "CASTER",
          points = {
              [1] = {
                  ["Convection"] = 5,
                  ["Concussion"] = 5,
                  ["Elemental Warding"] = 3,
                  ["Elemental Focus"] = 1,
                  ["Reverberation"] = 1,
                  ["Call of Thunder"] = 5,
                  ["Elemental Fury"] = 1,
                  ["Unrelenting Storm"] = 5,
                  ["Elemental Precision"] = 3,
                  ["Lightning Mastery"] = 5,
                  ["Elemental Mastery"] = 1,
                  ["Lightning Overload"] = 5,
                  ["Totem of Wrath"] = 1,
              },
              [3] = {
                  ["Tidal Focus"] = 5,
                  ["Totemic Focus"] = 5,
                  ["Nature's Guidance"] = 3,
                  ["Totemic Mastery"] = 1,
                  ["Healing Focus"] = 1,
                  ["Tidal Mastery"] = 5,
              },
          },
          stats = {
              "Spell hit to 16% (202 rating; Elemental Precision and Nature's Guidance cover 9%)",
              "Spell damage",
              "Spell crit",
              "Spell haste",
              "Intellect",
              "MP5",
          },
          notes = "The 41/0/20 Totem of Wrath raid build. Lightning Bolt is the filler around Chain Lightning on cooldown, with Totem of Wrath planted for the caster group and Elemental Mastery saved for burst or movement; Water Shield plus Unrelenting Storm keeps the mana bar honest. The Reverberation point and the single Healing Focus point are floats - Storm Reach, Eye of the Storm and Healing Grace are common swaps." },
        { key = "ENHANCEMENT", name = "Enhancement", role = "MELEE",
          points = {
              [1] = {
                  ["Convection"] = 5,
                  ["Concussion"] = 5,
                  ["Elemental Focus"] = 1,
                  ["Reverberation"] = 5,
              },
              [2] = {
                  ["Ancestral Knowledge"] = 5,
                  ["Thundering Strikes"] = 5,
                  ["Improved Ghost Wolf"] = 2,
                  ["Enhancing Totems"] = 2,
                  ["Shamanistic Focus"] = 1,
                  ["Flurry"] = 5,
                  ["Improved Weapon Totems"] = 2,
                  ["Spirit Weapons"] = 1,
                  ["Elemental Weapons"] = 3,
                  ["Mental Quickness"] = 3,
                  ["Weapon Mastery"] = 5,
                  ["Dual Wield"] = 1,
                  ["Dual Wield Specialization"] = 3,
                  ["Stormstrike"] = 1,
                  ["Unleashed Rage"] = 5,
                  ["Shamanistic Rage"] = 1,
              },
          },
          stats = {
              "Melee hit to 9% (142 rating) special cap; Dual Wield Specialization counts for 6%",
              "Expertise (26 caps boss dodge)",
              "Attack power",
              "Crit rating",
              "Haste rating",
              "Stamina",
          },
          notes = "The 16/45/0 dual-wield raid build. Windfury on two slow weapons, Stormstrike and Earth Shock on cooldown, and Windfury Totem twisted with Grace of Air for the melee group; Shamanistic Rage sustains mana and doubles as a 30% damage-reduction wall. The Improved Ghost Wolf points are flex - Anticipation, Toughness or Improved Lightning Shield are common swaps." },
        { key = "RESTORATION", name = "Restoration", role = "HEALER",
          points = {
              [2] = {
                  ["Ancestral Knowledge"] = 5,
              },
              [3] = {
                  ["Improved Healing Wave"] = 5,
                  ["Tidal Focus"] = 5,
                  ["Ancestral Healing"] = 3,
                  ["Totemic Focus"] = 5,
                  ["Healing Focus"] = 5,
                  ["Totemic Mastery"] = 1,
                  ["Healing Grace"] = 3,
                  ["Restorative Totems"] = 5,
                  ["Tidal Mastery"] = 5,
                  ["Healing Way"] = 3,
                  ["Nature's Swiftness"] = 1,
                  ["Focused Mind"] = 3,
                  ["Purification"] = 5,
                  ["Mana Tide Totem"] = 1,
                  ["Improved Chain Heal"] = 2,
                  ["Nature's Blessing"] = 3,
                  ["Earth Shield"] = 1,
              },
          },
          stats = {
              "Bonus healing",
              "MP5",
              "Intellect",
              "Spell crit",
              "Spell haste",
              "Stamina",
          },
          notes = "The 0/5/56 Earth Shield chain-heal raid build. Keep Earth Shield on the tank and Water Shield on yourself, then Chain Heal stacked groups - with 2/2 Improved Chain Heal it is most of your casting - while Mana Tide covers the healer group and Nature's Swiftness plus Healing Wave is the emergency button. Focused Mind, Healing Way and Healing Grace points can flex into Nature's Guardian or Nature's Guidance." },
    },
}
