-- Commander_Talents — DRUID talent data (GENERATED 2026-08-04).
-- TBC 2.4.3 final talent state. Regenerate via an agent pass against
-- prompts/commander-talents.md; after any hand-edit, re-run
-- Harness/validate_class_data.lua.

CommanderTalentsData.Classes.DRUID = {
    trees = {
        {
            name = "Balance", bg = "DruidBalance",
            talents = {
                { name = "Starlight Wrath", icon = "spell_nature_abolishmagic", row = 1, col = 1, max = 5,
                  ranks = {
                      "Reduces the cast time of your Wrath and Starfire spells by 0.1 sec.",
                      "Reduces the cast time of your Wrath and Starfire spells by 0.2 sec.",
                      "Reduces the cast time of your Wrath and Starfire spells by 0.3 sec.",
                      "Reduces the cast time of your Wrath and Starfire spells by 0.4 sec.",
                      "Reduces the cast time of your Wrath and Starfire spells by 0.5 sec.",
                  } },
                { name = "Nature's Grasp", icon = "spell_nature_natureswrath", row = 1, col = 2, max = 1,
                  ranks = {
                      "While active, any time an enemy strikes the caster they have a 35% chance to become afflicted by Entangling Roots (Rank 1). Only useable outdoors. 1 charge. Lasts 45 sec.",
                  } },
                { name = "Improved Nature's Grasp", icon = "spell_nature_natureswrath", row = 1, col = 3, max = 4, req = "Nature's Grasp",
                  req = "Nature's Grasp",
                  ranks = {
                      "Increases the chance for your Nature's Grasp to entangle an enemy by 15%.",
                      "Increases the chance for your Nature's Grasp to entangle an enemy by 30%.",
                      "Increases the chance for your Nature's Grasp to entangle an enemy by 45%.",
                      "Increases the chance for your Nature's Grasp to entangle an enemy by 65%.",
                  } },
                { name = "Control of Nature", icon = "spell_nature_stranglevines", row = 2, col = 1, max = 3,
                  ranks = {
                      "Gives you a 40% chance to avoid interruption caused by damage while casting Entangling Roots and Cyclone.",
                      "Gives you a 70% chance to avoid interruption caused by damage while casting Entangling Roots and Cyclone.",
                      "Gives you a 100% chance to avoid interruption caused by damage while casting Entangling Roots and Cyclone.",
                  } },
                { name = "Focused Starlight", icon = "inv_staff_01", row = 2, col = 2, max = 2,
                  ranks = {
                      "Increases the critical strike chance of your Wrath and Starfire spells by 2%.",
                      "Increases the critical strike chance of your Wrath and Starfire spells by 4%.",
                  } },
                { name = "Improved Moonfire", icon = "spell_nature_starfall", row = 2, col = 3, max = 2,
                  ranks = {
                      "Increases the damage and critical strike chance of your Moonfire spell by 5%.",
                      "Increases the damage and critical strike chance of your Moonfire spell by 10%.",
                  } },
                { name = "Brambles", icon = "spell_nature_thorns", row = 3, col = 1, max = 3,
                  ranks = {
                      "Increases damage caused by your Thorns and Entangling Roots spells by 25%.",
                      "Increases damage caused by your Thorns and Entangling Roots spells by 50%.",
                      "Increases damage caused by your Thorns and Entangling Roots spells by 75%.",
                  } },
                { name = "Insect Swarm", icon = "spell_nature_insectswarm", row = 3, col = 3, max = 1,
                  ranks = {
                      "The enemy target is swarmed by insects, decreasing their chance to hit by 2% and causing 108 Nature damage over 12 sec.",
                  } },
                { name = "Nature's Reach", icon = "spell_nature_naturetouchgrow", row = 3, col = 4, max = 2,
                  ranks = {
                      "Increases the range of your Balance spells and Faerie Fire (Feral) ability by 10%.",
                      "Increases the range of your Balance spells and Faerie Fire (Feral) ability by 20%.",
                  } },
                { name = "Vengeance", icon = "spell_nature_purge", row = 4, col = 2, max = 5, req = "Focused Starlight",
                  req = "Focused Starlight",
                  ranks = {
                      "Increases the critical strike damage bonus of your Starfire, Moonfire, and Wrath spells by 20%.",
                      "Increases the critical strike damage bonus of your Starfire, Moonfire, and Wrath spells by 40%.",
                      "Increases the critical strike damage bonus of your Starfire, Moonfire, and Wrath spells by 60%.",
                      "Increases the critical strike damage bonus of your Starfire, Moonfire, and Wrath spells by 80%.",
                      "Increases the critical strike damage bonus of your Starfire, Moonfire, and Wrath spells by 100%.",
                  } },
                { name = "Celestial Focus", icon = "spell_arcane_starfire", row = 4, col = 3, max = 3,
                  ranks = {
                      "Gives your Starfire spell a 5% chance to stun the target for 3 sec and increases the chance you'll resist spell interruption when casting your Wrath spell by 25%.",
                      "Gives your Starfire spell a 10% chance to stun the target for 3 sec and increases the chance you'll resist spell interruption when casting your Wrath spell by 50%.",
                      "Gives your Starfire spell a 15% chance to stun the target for 3 sec and increases the chance you'll resist spell interruption when casting your Wrath spell by 70%.",
                  } },
                { name = "Lunar Guidance", icon = "ability_druid_lunarguidance", row = 5, col = 1, max = 3,
                  ranks = {
                      "Increases your spell damage and healing by 8% of your total Intellect.",
                      "Increases your spell damage and healing by 16% of your total Intellect.",
                      "Increases your spell damage and healing by 25% of your total Intellect.",
                  } },
                { name = "Nature's Grace", icon = "spell_nature_naturesblessing", row = 5, col = 2, max = 1,
                  ranks = {
                      "All spell criticals grace you with a blessing of nature, reducing the casting time of your next spell by 0.5 sec.",
                  } },
                { name = "Moonglow", icon = "spell_nature_sentinal", row = 5, col = 3, max = 3,
                  ranks = {
                      "Reduces the Mana cost of your Moonfire, Starfire, Wrath, Healing Touch, Regrowth and Rejuvenation spells by 3%.",
                      "Reduces the Mana cost of your Moonfire, Starfire, Wrath, Healing Touch, Regrowth and Rejuvenation spells by 6%.",
                      "Reduces the Mana cost of your Moonfire, Starfire, Wrath, Healing Touch, Regrowth and Rejuvenation spells by 9%.",
                  } },
                { name = "Moonfury", icon = "spell_nature_moonglow", row = 6, col = 2, max = 5, req = "Nature's Grace",
                  req = "Nature's Grace",
                  ranks = {
                      "Increases the damage done by your Starfire, Moonfire and Wrath spells by 2%.",
                      "Increases the damage done by your Starfire, Moonfire and Wrath spells by 4%.",
                      "Increases the damage done by your Starfire, Moonfire and Wrath spells by 6%.",
                      "Increases the damage done by your Starfire, Moonfire and Wrath spells by 8%.",
                      "Increases the damage done by your Starfire, Moonfire and Wrath spells by 10%.",
                  } },
                { name = "Balance of Power", icon = "ability_druid_balanceofpower", row = 6, col = 3, max = 2,
                  ranks = {
                      "Increases your chance to hit with all spells and reduces the chance you'll be hit by spells by 2%.",
                      "Increases your chance to hit with all spells and reduces the chance you'll be hit by spells by 4%.",
                  } },
                { name = "Dreamstate", icon = "ability_druid_dreamstate", row = 7, col = 1, max = 3,
                  ranks = {
                      "Regenerate mana equal to 4% of your Intellect every 5 sec, even while casting.",
                      "Regenerate mana equal to 7% of your Intellect every 5 sec, even while casting.",
                      "Regenerate mana equal to 10% of your Intellect every 5 sec, even while casting.",
                  } },
                { name = "Moonkin Form", icon = "spell_nature_forceofnature", row = 7, col = 2, max = 1,
                  ranks = {
                      "Shapeshift into Moonkin Form. While in this form the armor contribution from items is increased by 400%, attack power is increased by 150% of your level and all party members within 30 yards have their spell critical chance increased by 5%. Melee attacks in this form have a chance on hit to regenerate mana based on attack power. The Moonkin can only cast Balance and Remove Curse spells while shapeshifted. The act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.",
                  } },
                { name = "Improved Faerie Fire", icon = "spell_nature_faeriefire", row = 7, col = 3, max = 3,
                  ranks = {
                      "Your Faerie Fire spell also increases the chance the target will be hit by melee and ranged attacks by 1%.",
                      "Your Faerie Fire spell also increases the chance the target will be hit by melee and ranged attacks by 2%.",
                      "Your Faerie Fire spell also increases the chance the target will be hit by melee and ranged attacks by 3%.",
                  } },
                { name = "Wrath of Cenarius", icon = "ability_druid_twilightswrath", row = 8, col = 2, max = 5,
                  ranks = {
                      "Your Starfire spell gains an additional 4% and your Wrath gains an additional 2% of your bonus damage effects.",
                      "Your Starfire spell gains an additional 8% and your Wrath gains an additional 4% of your bonus damage effects.",
                      "Your Starfire spell gains an additional 12% and your Wrath gains an additional 6% of your bonus damage effects.",
                      "Your Starfire spell gains an additional 16% and your Wrath gains an additional 8% of your bonus damage effects.",
                      "Your Starfire spell gains an additional 20% and your Wrath gains an additional 10% of your bonus damage effects.",
                  } },
                { name = "Force of Nature", icon = "ability_druid_forceofnature", row = 9, col = 2, max = 1,
                  ranks = {
                      "Summons 3 treants to attack enemy targets for 30 sec.",
                  } },
            },
        },
        {
            name = "Feral Combat", bg = "DruidFeralCombat",
            talents = {
                { name = "Ferocity", icon = "ability_hunter_pet_hyena", row = 1, col = 2, max = 5,
                  ranks = {
                      "Reduces the cost of your Maul, Swipe, Claw, Rake and Mangle abilities by 1 Rage or Energy.",
                      "Reduces the cost of your Maul, Swipe, Claw, Rake and Mangle abilities by 2 Rage or Energy.",
                      "Reduces the cost of your Maul, Swipe, Claw, Rake and Mangle abilities by 3 Rage or Energy.",
                      "Reduces the cost of your Maul, Swipe, Claw, Rake and Mangle abilities by 4 Rage or Energy.",
                      "Reduces the cost of your Maul, Swipe, Claw, Rake and Mangle abilities by 5 Rage or Energy.",
                  } },
                { name = "Feral Aggression", icon = "classic_ability_druid_demoralizingroar", row = 1, col = 3, max = 5,
                  ranks = {
                      "Increases the attack power reduction of your Demoralizing Roar by 8% and the damage caused by your Ferocious Bite by 3%.",
                      "Increases the attack power reduction of your Demoralizing Roar by 16% and the damage caused by your Ferocious Bite by 6%.",
                      "Increases the attack power reduction of your Demoralizing Roar by 24% and the damage caused by your Ferocious Bite by 9%.",
                      "Increases the attack power reduction of your Demoralizing Roar by 32% and the damage caused by your Ferocious Bite by 12%.",
                      "Increases the attack power reduction of your Demoralizing Roar by 40% and the damage caused by your Ferocious Bite by 15%.",
                  } },
                { name = "Feral Instinct", icon = "ability_ambush", row = 2, col = 1, max = 3,
                  ranks = {
                      "Increases threat caused in Bear and Dire Bear Form by 5% and reduces the chance enemies have to detect you while Prowling.",
                      "Increases threat caused in Bear and Dire Bear Form by 10% and reduces the chance enemies have to detect you while Prowling.",
                      "Increases threat caused in Bear and Dire Bear Form by 15% and reduces the chance enemies have to detect you while Prowling.",
                  } },
                { name = "Brutal Impact", icon = "ability_druid_bash", row = 2, col = 2, max = 2,
                  ranks = {
                      "Increases the stun duration of your Bash and Pounce abilities by 0.5 sec.",
                      "Increases the stun duration of your Bash and Pounce abilities by 1 sec.",
                  } },
                { name = "Thick Hide", icon = "inv_misc_pelt_bear_03", row = 2, col = 3, max = 3,
                  ranks = {
                      "Increases your Armor contribution from items by 4%.",
                      "Increases your Armor contribution from items by 7%.",
                      "Increases your Armor contribution from items by 10%.",
                  } },
                { name = "Feral Swiftness", icon = "spell_nature_spiritwolf", row = 3, col = 1, max = 2,
                  ranks = {
                      "Increases your movement speed by 15% while outdoors in Cat Form and increases your chance to dodge while in Cat Form, Bear Form and Dire Bear Form by 2%.",
                      "Increases your movement speed by 30% while outdoors in Cat Form and increases your chance to dodge while in Cat Form, Bear Form and Dire Bear Form by 4%.",
                  } },
                { name = "Feral Charge", icon = "ability_hunter_pet_bear", row = 3, col = 2, max = 1,
                  ranks = {
                      "Causes you to charge an enemy, immobilizing and interrupting any spell being cast for 4 sec.",
                  } },
                { name = "Sharpened Claws", icon = "inv_misc_monsterclaw_04", row = 3, col = 3, max = 3,
                  ranks = {
                      "Increases your critical strike chance while in Bear, Dire Bear or Cat Form by 2%.",
                      "Increases your critical strike chance while in Bear, Dire Bear or Cat Form by 4%.",
                      "Increases your critical strike chance while in Bear, Dire Bear or Cat Form by 6%.",
                  } },
                { name = "Shredding Attacks", icon = "spell_shadow_vampiricaura", row = 4, col = 1, max = 2,
                  ranks = {
                      "Reduces the energy cost of your Shred ability by 9 and the rage cost of your Lacerate ability by 1.",
                      "Reduces the energy cost of your Shred ability by 18 and the rage cost of your Lacerate ability by 2.",
                  } },
                { name = "Predatory Strikes", icon = "ability_hunter_pet_cat", row = 4, col = 2, max = 3,
                  ranks = {
                      "Increases your melee attack power in Cat, Bear, Dire Bear and Moonkin Forms by 50% of your level.",
                      "Increases your melee attack power in Cat, Bear, Dire Bear and Moonkin Forms by 100% of your level.",
                      "Increases your melee attack power in Cat, Bear, Dire Bear and Moonkin Forms by 150% of your level.",
                  } },
                { name = "Primal Fury", icon = "ability_racial_cannibalize", row = 4, col = 3, max = 2,
                  req = "Sharpened Claws",
                  ranks = {
                      "Gives you a 50% chance to gain an additional 5 Rage anytime you get a critical strike while in Bear and Dire Bear Form and your critical strikes from Cat Form abilities that add combo points have a 50% chance to add an additional combo point.",
                      "Gives you a 100% chance to gain an additional 5 Rage anytime you get a critical strike while in Bear and Dire Bear Form and your critical strikes from Cat Form abilities that add combo points have a 100% chance to add an additional combo point.",
                  } },
                { name = "Savage Fury", icon = "ability_druid_ravage", row = 5, col = 1, max = 2,
                  ranks = {
                      "Increases the damage caused by your Claw, Rake, and Mangle (Cat) abilities by 10%.",
                      "Increases the damage caused by your Claw, Rake, and Mangle (Cat) abilities by 20%.",
                  } },
                { name = "Faerie Fire (Feral)", icon = "spell_nature_faeriefire", row = 5, col = 3, max = 1,
                  ranks = {
                      "Decrease the armor of the target by 175 for 40 sec. While affected, the target cannot stealth or turn invisible.",
                  } },
                { name = "Nurturing Instinct", icon = "ability_druid_healinginstincts", row = 5, col = 4, max = 2,
                  ranks = {
                      "Increases your healing spells by up to 50% of your Agility, and increases healing done to you by 10% while in Cat form.",
                      "Increases your healing spells by up to 100% of your Agility, and increases healing done to you by 20% while in Cat form.",
                  } },
                { name = "Heart of the Wild", icon = "spell_holy_blessingofagility", row = 6, col = 2, max = 5, req = "Predatory Strikes",
                  req = "Predatory Strikes",
                  ranks = {
                      "Increases your Intellect by 4%. In addition, while in Bear or Dire Bear Form your Stamina is increased by 4% and while in Cat Form your attack power is increased by 2%.",
                      "Increases your Intellect by 8%. In addition, while in Bear or Dire Bear Form your Stamina is increased by 8% and while in Cat Form your attack power is increased by 4%.",
                      "Increases your Intellect by 12%. In addition, while in Bear or Dire Bear Form your Stamina is increased by 12% and while in Cat Form your attack power is increased by 6%.",
                      "Increases your Intellect by 16%. In addition, while in Bear or Dire Bear Form your Stamina is increased by 16% and while in Cat Form your attack power is increased by 8%.",
                      "Increases your Intellect by 20%. In addition, while in Bear or Dire Bear Form your Stamina is increased by 20% and while in Cat Form your attack power is increased by 10%.",
                  } },
                { name = "Survival of the Fittest", icon = "ability_druid_enrage", row = 6, col = 3, max = 3,
                  ranks = {
                      "Increases all attributes by 1% and reduces the chance you'll be critically hit by melee attacks by 1%.",
                      "Increases all attributes by 2% and reduces the chance you'll be critically hit by melee attacks by 2%.",
                      "Increases all attributes by 3% and reduces the chance you'll be critically hit by melee attacks by 3%.",
                  } },
                { name = "Primal Tenacity", icon = "ability_druid_primaltenacity", row = 7, col = 1, max = 3,
                  ranks = {
                      "Increases your chance to resist Stun and Fear mechanics by 5%.",
                      "Increases your chance to resist Stun and Fear mechanics by 10%.",
                      "Increases your chance to resist Stun and Fear mechanics by 15%.",
                  } },
                { name = "Leader of the Pack", icon = "spell_nature_unyeildingstamina", row = 7, col = 2, max = 1,
                  ranks = {
                      "While in Cat, Bear or Dire Bear Form, the Leader of the Pack increases ranged and melee critical chance of all party members within 45 yards by 5%.",
                  } },
                { name = "Improved Leader of the Pack", icon = "spell_nature_unyeildingstamina", row = 7, col = 3, max = 2, req = "Leader of the Pack",
                  req = "Leader of the Pack",
                  ranks = {
                      "Your Leader of the Pack ability also causes affected targets to have a 100% chance to heal themselves for 2% of their total health when they critically hit with a melee or ranged attack. The healing effect cannot occur more than once every 6 sec.",
                      "Your Leader of the Pack ability also causes affected targets to have a 100% chance to heal themselves for 4% of their total health when they critically hit with a melee or ranged attack. The healing effect cannot occur more than once every 6 sec.",
                  } },
                { name = "Predatory Instincts", icon = "ability_druid_predatoryinstincts", row = 8, col = 3, max = 5,
                  ranks = {
                      "While in Cat Form, Bear Form, or Dire Bear Form, increases your damage from melee critical strikes by 2% and your chance to avoid area effect attacks by 3%.",
                      "While in Cat Form, Bear Form, or Dire Bear Form, increases your damage from melee critical strikes by 4% and your chance to avoid area effect attacks by 6%.",
                      "While in Cat Form, Bear Form, or Dire Bear Form, increases your damage from melee critical strikes by 6% and your chance to avoid area effect attacks by 9%.",
                      "While in Cat Form, Bear Form, or Dire Bear Form, increases your damage from melee critical strikes by 8% and your chance to avoid area effect attacks by 12%.",
                      "While in Cat Form, Bear Form, or Dire Bear Form, increases your damage from melee critical strikes by 10% and your chance to avoid area effect attacks by 15%.",
                  } },
                { name = "Mangle", icon = "ability_druid_mangle2", row = 9, col = 2, max = 1, req = "Leader of the Pack",
                  req = "Leader of the Pack",
                  ranks = {
                      "Mangle the target, inflicting damage and causing the target to take additional damage from bleed effects for 12 sec. This ability can be used in Cat Form or Dire Bear Form.",
                  } },
            },
        },
        {
            name = "Restoration", bg = "DruidRestoration",
            talents = {
                { name = "Improved Mark of the Wild", icon = "spell_nature_regeneration", row = 1, col = 2, max = 5,
                  ranks = {
                      "Increases the effects of your Mark of the Wild and Gift of the Wild spells by 7%.",
                      "Increases the effects of your Mark of the Wild and Gift of the Wild spells by 14%.",
                      "Increases the effects of your Mark of the Wild and Gift of the Wild spells by 21%.",
                      "Increases the effects of your Mark of the Wild and Gift of the Wild spells by 28%.",
                      "Increases the effects of your Mark of the Wild and Gift of the Wild spells by 35%.",
                  } },
                { name = "Furor", icon = "spell_holy_blessingofstamina", row = 1, col = 3, max = 5,
                  ranks = {
                      "Gives you 20% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form or 40 Energy when you shapeshift into Cat Form.",
                      "Gives you 40% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form or 40 Energy when you shapeshift into Cat Form.",
                      "Gives you 60% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form or 40 Energy when you shapeshift into Cat Form.",
                      "Gives you 80% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form or 40 Energy when you shapeshift into Cat Form.",
                      "Gives you 100% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form or 40 Energy when you shapeshift into Cat Form.",
                  } },
                { name = "Naturalist", icon = "spell_nature_healingtouch", row = 2, col = 1, max = 5,
                  ranks = {
                      "Reduces the cast time of your Healing Touch spell by 0.1 sec and increases the damage you deal with physical attacks in all forms by 2%.",
                      "Reduces the cast time of your Healing Touch spell by 0.2 sec and increases the damage you deal with physical attacks in all forms by 4%.",
                      "Reduces the cast time of your Healing Touch spell by 0.3 sec and increases the damage you deal with physical attacks in all forms by 6%.",
                      "Reduces the cast time of your Healing Touch spell by 0.4 sec and increases the damage you deal with physical attacks in all forms by 8%.",
                      "Reduces the cast time of your Healing Touch spell by 0.5 sec and increases the damage you deal with physical attacks in all forms by 10%.",
                  } },
                { name = "Nature's Focus", icon = "spell_nature_healingwavegreater", row = 2, col = 2, max = 5,
                  ranks = {
                      "Gives you a 14% chance to avoid interruption caused by damage while casting the Healing Touch, Regrowth and Tranquility spells.",
                      "Gives you a 28% chance to avoid interruption caused by damage while casting the Healing Touch, Regrowth and Tranquility spells.",
                      "Gives you a 42% chance to avoid interruption caused by damage while casting the Healing Touch, Regrowth and Tranquility spells.",
                      "Gives you a 56% chance to avoid interruption caused by damage while casting the Healing Touch, Regrowth and Tranquility spells.",
                      "Gives you a 70% chance to avoid interruption caused by damage while casting the Healing Touch, Regrowth and Tranquility spells.",
                  } },
                { name = "Natural Shapeshifter", icon = "spell_nature_wispsplode", row = 2, col = 3, max = 3,
                  ranks = {
                      "Reduces the mana cost of all shapeshifting by 10%.",
                      "Reduces the mana cost of all shapeshifting by 20%.",
                      "Reduces the mana cost of all shapeshifting by 30%.",
                  } },
                { name = "Intensity", icon = "spell_frost_windwalkon", row = 3, col = 1, max = 3,
                  ranks = {
                      "Allows 10% of your Mana regeneration to continue while casting and causes your Enrage ability to instantly generate 4 rage.",
                      "Allows 20% of your Mana regeneration to continue while casting and causes your Enrage ability to instantly generate 7 rage.",
                      "Allows 30% of your Mana regeneration to continue while casting and causes your Enrage ability to instantly generate 10 rage.",
                  } },
                { name = "Subtlety", icon = "ability_eyeoftheowl", row = 3, col = 2, max = 5,
                  ranks = {
                      "Reduces the threat generated by your spells by 4% and reduces the chance your spells will be dispelled by 6%.",
                      "Reduces the threat generated by your spells by 8% and reduces the chance your spells will be dispelled by 12%.",
                      "Reduces the threat generated by your spells by 12% and reduces the chance your spells will be dispelled by 18%.",
                      "Reduces the threat generated by your spells by 16% and reduces the chance your spells will be dispelled by 24%.",
                      "Reduces the threat generated by your spells by 20% and reduces the chance your spells will be dispelled by 30%.",
                  } },
                { name = "Omen of Clarity", icon = "spell_nature_crystalball", row = 3, col = 3, max = 1,
                  ranks = {
                      "Imbues the Druid with natural energy. Each of the Druid's melee attacks has a chance of causing the caster to enter a Clearcasting state. The Clearcasting state reduces the Mana, Rage or Energy cost of your next damage or healing spell or offensive ability by 100%. Lasts 30 min.",
                  } },
                { name = "Tranquil Spirit", icon = "spell_holy_elunesgrace", row = 4, col = 2, max = 5,
                  ranks = {
                      "Reduces the mana cost of your Healing Touch and Tranquility spells by 2%.",
                      "Reduces the mana cost of your Healing Touch and Tranquility spells by 4%.",
                      "Reduces the mana cost of your Healing Touch and Tranquility spells by 6%.",
                      "Reduces the mana cost of your Healing Touch and Tranquility spells by 8%.",
                      "Reduces the mana cost of your Healing Touch and Tranquility spells by 10%.",
                  } },
                { name = "Improved Rejuvenation", icon = "spell_nature_rejuvenation", row = 4, col = 3, max = 3,
                  ranks = {
                      "Increases the effect of your Rejuvenation spell by 5%.",
                      "Increases the effect of your Rejuvenation spell by 10%.",
                      "Increases the effect of your Rejuvenation spell by 15%.",
                  } },
                { name = "Nature's Swiftness", icon = "spell_nature_ravenform", row = 5, col = 1, max = 1, req = "Intensity",
                  req = "Intensity",
                  ranks = {
                      "When activated, your next Nature spell becomes an instant cast spell.",
                  } },
                { name = "Gift of Nature", icon = "spell_nature_protectionformnature", row = 5, col = 2, max = 5,
                  ranks = {
                      "Increases the effect of all healing spells by 2%.",
                      "Increases the effect of all healing spells by 4%.",
                      "Increases the effect of all healing spells by 6%.",
                      "Increases the effect of all healing spells by 8%.",
                      "Increases the effect of all healing spells by 10%.",
                  } },
                { name = "Improved Tranquility", icon = "spell_nature_tranquility", row = 5, col = 4, max = 2,
                  ranks = {
                      "Reduces threat caused by Tranquility by 50%.",
                      "Reduces threat caused by Tranquility by 100%.",
                  } },
                { name = "Empowered Touch", icon = "ability_druid_empoweredtouch", row = 6, col = 1, max = 2,
                  ranks = {
                      "Your Healing Touch spell gains an additional 10% of your bonus healing effects.",
                      "Your Healing Touch spell gains an additional 20% of your bonus healing effects.",
                  } },
                { name = "Improved Regrowth", icon = "spell_nature_resistnature", row = 6, col = 3, max = 5, req = "Improved Rejuvenation",
                  req = "Improved Rejuvenation",
                  ranks = {
                      "Increases the critical effect chance of your Regrowth spell by 10%.",
                      "Increases the critical effect chance of your Regrowth spell by 20%.",
                      "Increases the critical effect chance of your Regrowth spell by 30%.",
                      "Increases the critical effect chance of your Regrowth spell by 40%.",
                      "Increases the critical effect chance of your Regrowth spell by 50%.",
                  } },
                { name = "Living Spirit", icon = "spell_nature_giftofthewaterspirit", row = 7, col = 1, max = 3,
                  ranks = {
                      "Increases your total Spirit by 5%.",
                      "Increases your total Spirit by 10%.",
                      "Increases your total Spirit by 15%.",
                  } },
                { name = "Swiftmend", icon = "inv_relics_idolofrejuvenation", row = 7, col = 2, max = 1, req = "Gift of Nature",
                  req = "Gift of Nature",
                  ranks = {
                      "Consumes a Rejuvenation or Regrowth effect on a friendly target to instantly heal them an amount equal to 12 sec. of Rejuvenation or 18 sec. of Regrowth.",
                  } },
                { name = "Natural Perfection", icon = "ability_druid_naturalperfection", row = 7, col = 3, max = 3,
                  ranks = {
                      "Your critical strike chance with all spells is increased by 1% and critical strikes against you give you the Natural Perfection effect reducing all damage taken by 2%. Stacks up to 3 times. Lasts 8 sec.",
                      "Your critical strike chance with all spells is increased by 2% and critical strikes against you give you the Natural Perfection effect reducing all damage taken by 3%. Stacks up to 3 times. Lasts 8 sec.",
                      "Your critical strike chance with all spells is increased by 3% and critical strikes against you give you the Natural Perfection effect reducing all damage taken by 4%. Stacks up to 3 times. Lasts 8 sec.",
                  } },
                { name = "Empowered Rejuvenation", icon = "ability_druid_empoweredrejuvination", row = 8, col = 2, max = 5,
                  ranks = {
                      "The bonus healing effects of your healing over time spells is increased by 4%.",
                      "The bonus healing effects of your healing over time spells is increased by 8%.",
                      "The bonus healing effects of your healing over time spells is increased by 12%.",
                      "The bonus healing effects of your healing over time spells is increased by 16%.",
                      "The bonus healing effects of your healing over time spells is increased by 20%.",
                  } },
                { name = "Tree of Life", icon = "ability_druid_treeoflife", row = 9, col = 2, max = 1,
                  ranks = {
                      "Shapeshift into the Tree of Life. While in this form you increase healing received by 25% of your total Spirit for all party members within 45 yards, your movement speed is reduced by 20%, and you can only cast Swiftmend, Innervate, Nature's Swiftness, Rebirth, Barkskin, poison removing and healing over time spells, but the mana cost of these spells is reduced by 20%. The act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.",
                  } },
            },
        },
    },
    builds = {
        { key = "BALANCE", name = "Balance", role = "CASTER",
          points = {
              [1] = {
                  ["Starlight Wrath"] = 5,
                  ["Nature's Grasp"] = 1,
                  ["Improved Nature's Grasp"] = 2,
                  ["Focused Starlight"] = 2,
                  ["Improved Moonfire"] = 2,
                  ["Insect Swarm"] = 1,
                  ["Nature's Reach"] = 2,
                  ["Vengeance"] = 5,
                  ["Celestial Focus"] = 3,
                  ["Lunar Guidance"] = 3,
                  ["Nature's Grace"] = 1,
                  ["Moonglow"] = 3,
                  ["Moonfury"] = 5,
                  ["Balance of Power"] = 2,
                  ["Dreamstate"] = 3,
                  ["Moonkin Form"] = 1,
                  ["Improved Faerie Fire"] = 3,
                  ["Wrath of Cenarius"] = 5,
                  ["Force of Nature"] = 1,
              },
              [3] = {
                  ["Improved Mark of the Wild"] = 5,
                  ["Furor"] = 3,
                  ["Natural Shapeshifter"] = 3,
              },
          },
          stats = {
              "Spell Hit to 16% / 202 rating (Balance of Power covers 4%, so ~152 from gear)",
              "Spell Damage",
              "Spell Crit",
              "Spell Haste",
              "Intellect (Lunar Guidance and Dreamstate scale it)",
              "MP5 / Spirit",
          },
          notes = "The 50/0/11 Moonkin raid build: Starfire spam with Moonfire and Insect Swarm rolling, Dreamstate plus Innervate carrying the mana bar. The Nature's Grasp line and the resto splash beyond Improved Mark of the Wild are pure filler; Brambles or Control of Nature are equally legal parking spots." },
        { key = "FERAL_CAT", name = "Feral Cat", role = "MELEE",
          points = {
              [2] = {
                  ["Ferocity"] = 5,
                  ["Feral Aggression"] = 2,
                  ["Feral Instinct"] = 3,
                  ["Brutal Impact"] = 2,
                  ["Feral Swiftness"] = 2,
                  ["Feral Charge"] = 1,
                  ["Sharpened Claws"] = 3,
                  ["Shredding Attacks"] = 2,
                  ["Predatory Strikes"] = 3,
                  ["Primal Fury"] = 2,
                  ["Savage Fury"] = 2,
                  ["Faerie Fire (Feral)"] = 1,
                  ["Nurturing Instinct"] = 2,
                  ["Heart of the Wild"] = 5,
                  ["Survival of the Fittest"] = 3,
                  ["Leader of the Pack"] = 1,
                  ["Improved Leader of the Pack"] = 2,
                  ["Predatory Instincts"] = 5,
                  ["Mangle"] = 1,
              },
              [3] = {
                  ["Furor"] = 5,
                  ["Naturalist"] = 5,
                  ["Natural Shapeshifter"] = 3,
                  ["Omen of Clarity"] = 1,
              },
          },
          stats = {
              "Melee Hit to 9% / 142 rating",
              "Expertise (26 for the dodge cap)",
              "Agility",
              "Strength / Attack Power",
              "Crit (feeds Primal Fury combo points)",
              "Armor Penetration",
          },
          notes = "The 0/47/14 powershifting cat: Shred and Mangle, then shift out and back with Furor plus Wolfshead Helm for a fresh energy bar while Omen of Clarity hands out free specials. Feral Aggression, Brutal Impact and Nurturing Instinct are the flex filler points." },
        { key = "FERAL_BEAR", name = "Feral Bear", role = "TANK",
          points = {
              [2] = {
                  ["Ferocity"] = 5,
                  ["Feral Instinct"] = 3,
                  ["Thick Hide"] = 3,
                  ["Feral Swiftness"] = 2,
                  ["Feral Charge"] = 1,
                  ["Sharpened Claws"] = 3,
                  ["Shredding Attacks"] = 2,
                  ["Predatory Strikes"] = 3,
                  ["Primal Fury"] = 2,
                  ["Savage Fury"] = 2,
                  ["Faerie Fire (Feral)"] = 1,
                  ["Heart of the Wild"] = 5,
                  ["Survival of the Fittest"] = 3,
                  ["Leader of the Pack"] = 1,
                  ["Improved Leader of the Pack"] = 2,
                  ["Predatory Instincts"] = 5,
                  ["Mangle"] = 1,
              },
              [3] = {
                  ["Furor"] = 5,
                  ["Naturalist"] = 5,
                  ["Natural Shapeshifter"] = 3,
                  ["Intensity"] = 3,
                  ["Omen of Clarity"] = 1,
              },
          },
          stats = {
              "Crit immunity: 2.6% from Defense or Resilience (Survival of the Fittest covers 3% of the 5.6%)",
              "Agility (dodge, armor and crit)",
              "Stamina",
              "Armor (Thick Hide multiplies it)",
              "Expertise / Hit for threat",
              "Strength",
          },
          notes = "The 0/44/17 raid bear: Mangle and Lacerate with Maul weaving for threat, and Furor plus Intensity banking 20 rage before every pull for snap aggro. Trades the cat's stun and filler points for Thick Hide and the deeper resto splash; Feral Aggression is the classic swap if you must keep Demoralizing Roar improved." },
        { key = "RESTORATION", name = "Restoration", role = "HEALER",
          points = {
              [3] = {
                  ["Improved Mark of the Wild"] = 5,
                  ["Naturalist"] = 5,
                  ["Nature's Focus"] = 5,
                  ["Natural Shapeshifter"] = 3,
                  ["Intensity"] = 3,
                  ["Subtlety"] = 5,
                  ["Omen of Clarity"] = 1,
                  ["Tranquil Spirit"] = 5,
                  ["Improved Rejuvenation"] = 3,
                  ["Nature's Swiftness"] = 1,
                  ["Gift of Nature"] = 5,
                  ["Empowered Touch"] = 2,
                  ["Improved Regrowth"] = 5,
                  ["Living Spirit"] = 3,
                  ["Swiftmend"] = 1,
                  ["Natural Perfection"] = 3,
                  ["Empowered Rejuvenation"] = 5,
                  ["Tree of Life"] = 1,
              },
          },
          stats = {
              "Bonus Healing",
              "MP5",
              "Spirit (Living Spirit and the Tree of Life aura scale it)",
              "Intellect",
              "Spell Haste",
          },
          notes = "The 0/0/61 Tree of Life raid build: Lifebloom rolling on tanks, Rejuvenation blanketing the raid, Swiftmend for triage, with Empowered Rejuvenation scaling every HoT tick. Furor and Improved Tranquility are the deliberate skips; Tranquil Spirit and Empowered Touch points can slide toward a Healing Touch style instead." },
    },
}
